(()=>{'use strict';
const ADMIN_NAME='RUBANSU1';
const toast=m=>window.toast?window.toast(m):alert(m);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function cards(){return Array.isArray(window.CARDS)?window.CARDS:[]}
async function refresh(){try{if(window.CR_REFRESH_PROFILE){await window.CR_REFRESH_PROFILE();return}const me=window.user||(await window.sb?.auth?.getSession())?.data?.session?.user;if(!me||!window.sb)return;const q=await window.sb.from('profiles').select('*').eq('id',me.id).single();if(!q.error&&q.data){window.profile=q.data;document.querySelectorAll('#gem-count,#gemCount').forEach(e=>e.textContent=q.data.gems);document.querySelectorAll('#gold-count,#goldCount').forEach(e=>e.textContent=q.data.gold);}}catch(e){console.warn('refresh admin',e)}}
function build(){const admin=[...document.querySelectorAll('.roomModal')].find(x=>/ADMIN CROWN RIFT/i.test(x.textContent||''));if(!admin||document.getElementById('crAdminTools'))return;const panel=admin.querySelector('#adminPanel');if(!panel||panel.style.display==='none')return;const old=panel.querySelector('.rp');if(old)old.style.display='none';const tools=document.createElement('div');tools.id='crAdminTools';tools.className='rp';tools.innerHTML='<h3>👑 GIVE — ADMIN UNIQUEMENT</h3><div style="color:#ae9eb9;font-size:11px;margin-bottom:10px">Recherche simple d’un pseudo puis donne directement au joueur.</div><input id="admSearch" class="ri" placeholder="Rechercher un pseudo..." autocomplete="off"><div id="admResults" style="margin:6px 0"></div><div id="admTarget" style="color:#ffd23f;font-size:11px;margin:8px 0">Aucun joueur sélectionné</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><input id="admPieces" class="ri" type="number" min="0" value="0" placeholder="Pièces"><input id="admGems" class="ri" type="number" min="0" value="0" placeholder="Gemmes"></div><select id="admCard" class="ri"><option value="">Aucune carte</option>'+cards().map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+'</option>').join('')+'</select><input id="admQty" class="ri" type="number" min="1" value="1" placeholder="Quantité"><button id="admGive" class="rb rgold">🎁 DONNER</button><div id="admStatus" style="margin-top:8px;color:#ae9eb9;font-size:10px"></div>';panel.appendChild(tools);document.getElementById('admSearch').oninput=search;document.getElementById('admGive').onclick=give}
async function search(){const q=document.getElementById('admSearch').value.trim();const box=document.getElementById('admResults');if(!box)return;if(q.length<1){box.innerHTML='';return}const r=await window.sb.from('profiles').select('id,username,display_name').ilike('username','%'+q+'%').limit(8);if(r.error){box.textContent=r.error.message;return}box.innerHTML=r.data.map(x=>'<button class="rb" style="width:100%;text-align:left" data-id="'+x.id+'" data-name="'+esc(x.username)+'">👤 '+esc(x.username)+(x.display_name&&x.display_name!==x.username?' — '+esc(x.display_name):'')+'</button>').join('')||'<span style="color:#ae9eb9">Aucun joueur.</span>';box.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{window.crAdminTarget={id:b.dataset.id,name:b.dataset.name};document.getElementById('admTarget').textContent='🎯 Cible : '+b.dataset.name;box.innerHTML=''})}
async function give(){const me=window.user||(await window.sb?.auth?.getSession())?.data?.session?.user;if(!me||!window.sb)return toast('Connecte-toi d’abord.');if(String(window.profile?.username||'').toUpperCase()!==ADMIN_NAME)return toast('Accès admin refusé.');const t=window.crAdminTarget;if(!t)return toast('Recherche puis sélectionne un joueur.');const pieces=Math.max(0,parseInt(document.getElementById('admPieces').value)||0),gems=Math.max(0,parseInt(document.getElementById('admGems').value)||0),card=document.getElementById('admCard').value,qty=Math.max(1,parseInt(document.getElementById('admQty').value)||1);if(!pieces&&!gems&&!card)return toast('Choisis une récompense.');const r=await window.sb.rpc('admin_give_rewards',{p_target_id:t.id,p_pieces:pieces,p_gems:gems,p_card_id:card?parseInt(card):null,p_card_qty:card?qty:0});if(r.error)return toast('Erreur : '+r.error.message);await refresh();document.getElementById('admStatus').textContent='✅ Donné à '+t.name+' • ressources actualisées';toast('Récompense envoyée 🎁')}
window.addEventListener('load',()=>setTimeout(build,900));setInterval(build,1200);
})();
