(()=>{'use strict';
const toast=m=>window.toast?window.toast(m):alert(m);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const getAdminPassword=()=>window.crAdminPassword||document.getElementById('adminPass')?.value||'';
const cards=()=>Array.isArray(window.CARDS)?window.CARDS:[];
async function refresh(){try{if(window.CR_REFRESH_PROFILE)await window.CR_REFRESH_PROFILE();else{const me=window.user||(await window.sb?.auth?.getSession())?.data?.session?.user;if(me){const q=await window.sb.from('profiles').select('*').eq('id',me.id).single();if(!q.error)window.profile=q.data}}if(typeof window.renderAll==='function')window.renderAll();if(typeof window.renderCards==='function')window.renderCards()}catch(e){console.warn(e)}}
function playerLabel(x){const display=String(x.display_name||'').trim(),username=String(x.username||'').trim();return display&&display!==username?display+' (@'+username+')':(display||username||'Joueur')}
function build(){const admin=[...document.querySelectorAll('.roomModal')].find(x=>/ADMIN CROWN RIFT/i.test(x.textContent||''));if(!admin)return;const panel=admin.querySelector('#adminPanel');if(!panel||panel.style.display==='none'||document.getElementById('crAdminTools'))return;const password=getAdminPassword();if(!password)return;window.crAdminPassword=password;const tools=document.createElement('div');tools.id='crAdminTools';tools.className='rp';tools.innerHTML='<h3>👑 GIVE ADMIN</h3><div style="color:#4fe5a2;font-weight:900;margin:8px 0">✅ DROITS ADMIN ACTIVÉS</div><input id="admSearch" class="ri" placeholder="Prénom / pseudo du joueur..."><div id="admResults" style="margin:6px 0"></div><div id="admTarget" style="color:#ffd23f;font-size:11px;margin:8px 0">Aucune cible</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><input id="admPieces" class="ri" type="number" min="0" value="0" placeholder="Pièces 🪙"><input id="admGems" class="ri" type="number" min="0" value="0" placeholder="Gemmes 💎"></div><select id="admCard" class="ri"><option value="">Aucune carte</option>'+cards().map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name)+'</option>').join('')+'</select><input id="admQty" class="ri" type="number" min="1" value="1" placeholder="Quantité carte"><button id="admGive" class="rb rgold">🎁 DONNER</button><button id="admLock" class="rb rred">🔒 VERROUILLER</button><div id="admStatus" style="margin-top:8px;color:#ae9eb9;font-size:10px"></div>';panel.appendChild(tools);document.getElementById('admSearch').oninput=search;document.getElementById('admGive').onclick=give;document.getElementById('admLock').onclick=lock}
function lock(){window.crAdminPassword='';window.crAdminTarget=null;document.getElementById('crAdminTools')?.remove();document.getElementById('adminPanel').style.display='none';document.getElementById('adminAuth').style.display='block';const p=document.getElementById('adminPass');if(p)p.value=''}
async function search(){const password=getAdminPassword(),q=document.getElementById('admSearch').value.trim(),box=document.getElementById('admResults');if(!password||!q){box.innerHTML='';return}const r=await window.sb.rpc('admin_find_players_v3',{p_admin_password:password,p_query:q});if(r.error){box.textContent='❌ '+r.error.message;return}box.innerHTML=r.data?.map(x=>'<button class="rb" style="width:100%;text-align:left;margin-bottom:5px" data-id="'+x.id+'" data-name="'+esc(playerLabel(x))+'">👤 '+esc(playerLabel(x))+'</button>').join('')||'<span style="color:#ae9eb9">Aucun joueur.</span>';box.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{window.crAdminTarget={id:b.dataset.id,name:b.dataset.name};document.getElementById('admTarget').textContent='🎯 '+b.dataset.name;box.innerHTML=''})}
async function give(){const password=getAdminPassword();if(!password)return toast('Déverrouille d’abord l’admin.');const me=window.user||(await window.sb?.auth?.getSession())?.data?.session?.user;if(!me||!window.sb)return toast('Connecte-toi d’abord.');const t=window.crAdminTarget;if(!t)return toast('Sélectionne un joueur.');const pieces=Math.max(0,parseInt(document.getElementById('admPieces').value)||0),gems=Math.max(0,parseInt(document.getElementById('admGems').value)||0),card=document.getElementById('admCard').value,qty=Math.max(1,parseInt(document.getElementById('admQty').value)||1);if(pieces===0&&gems===0&&!card)return toast('Choisis une récompense.');const r=await window.sb.rpc('admin_give_rewards_v3',{p_target_id:t.id,p_pieces:pieces,p_gems:gems,p_card_id:card?Number(card):null,p_card_qty:card?qty:0,p_admin_password:password});if(r.error){document.getElementById('admStatus').textContent='❌ '+r.error.message;return toast('GIVE impossible : '+r.error.message)}if(r.data){window.crAdminLastReward=r.data}await refresh();window.dispatchEvent(new CustomEvent('crAdminReward'));document.getElementById('admStatus').textContent='✅ GIVE réussi → '+t.name;toast('✅ Récompense envoyée à '+t.name)}
window.addEventListener('load',()=>setTimeout(build,900));setInterval(build,1200);
})();
