(()=>{'use strict';
let installed=false;
const A=()=>window.CROWN_RIFT_DECK?window.CROWN_RIFT_DECK():[];
function install(){if(installed)return;if(typeof window.startBotBattle!=='function')return;installed=true;const oldStart=window.startBotBattle;window.startBotBattle=function(){oldStart();setTimeout(setupArena,40)};const oldEnd=window.endBattle;window.endBattle=function(){window.__crBattleFixStop?.();oldEnd()};window.__crBattleFixStop=()=>{if(window.__crBattleFixTimer)clearInterval(window.__crBattleFixTimer);window.__crBattleFixTimer=null}}
function setupArena(){const arena=document.getElementById('arena');if(!arena||!window.battle)return;let chest=arena.querySelector('#crEnemyChest');if(!chest){chest=document.createElement('div');chest.id='crEnemyChest';chest.textContent='🪙';chest.title='Coffre du Rift';chest.style.cssText='position:absolute;top:3%;left:calc(50% - 31px);width:62px;height:54px;border-radius:14px;display:grid;place-items:center;font-size:30px;background:linear-gradient(#ffd966,#9d5a14);border:2px solid #fff8;box-shadow:0 0 30px #ffd23f55;z-index:6';arena.appendChild(chest)}const style=document.getElementById('crBridgeFixStyle')||document.createElement('style');style.id='crBridgeFixStyle';style.textContent=`#arena .bridge{z-index:5;box-shadow:inset 0 0 10px #0005}#arena .unit{transition:left .16s linear,top .16s linear}#crBattleInfo{position:absolute;left:10px;right:10px;bottom:10px;z-index:25;display:flex;justify-content:center;pointer-events:none}.crBI{padding:7px 11px;border-radius:99px;background:#09060ed9;border:1px solid #ffffff18;color:#fff;font-size:10px;font-weight:900}`;document.head.appendChild(style);if(!document.getElementById('crBattleInfo'))arena.insertAdjacentHTML('beforeend','<div id="crBattleInfo"><div class="crBI">🃏 Vaincs les gardes → traverse le pont → attaque le coffre.</div></div>');window.__crBattleFixStop?.();window.__crBattleFixTimer=setInterval(step,120)}
function units(){return Array.isArray(window.battle?.units)?window.battle.units:[]}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function hpbar(u){const i=u.element?.querySelector('.uhp i');if(i)i.style.width=Math.max(0,u.hp/u.maxHp*100)+'%'}
function kill(u){u.hp=0;u.element?.remove();window.battle.units=window.battle.units.filter(x=>x!==u)}
function hit(a,t){if(!t||t.hp<=0)return;t.hp-=Math.max(8,a.card.atk);t.element?.classList.add('hit');setTimeout(()=>t.element?.classList.remove('hit'),150);hpbar(t);if(t.hp<=0)kill(t)}
function nearestEnemy(u,all){return all.filter(x=>x.side!==u.side&&x.hp>0).sort((a,b)=>dist(u,a)-dist(u,b))[0]||null}
function steerBridge(u){const bridgeX=u.x<50?25.5:74.5;u.x+=(bridgeX-u.x)*.08}
function step(){const b=window.battle,a=document.getElementById('arena');if(!b||b.done||!a)return;const all=units(),enemies=all.filter(u=>u.side==='enemy'&&u.hp>0);b.energy=Math.min(10,(b.energy||0)+.065);for(const u of [...all]){if(!u.element||u.hp<=0)continue;u.cd=(u.cd||0)-120;const target=nearestEnemy(u,all);if(target&&dist(u,target)<=Math.max(30,(u.card.range||40)/1.3)){if(u.cd<=0){hit(u,target);u.cd=u.card.rate||1000}continue}
 const dir=u.side==='player'?-1:1;const speed=u.card.speed*.16;
 if(!target){if(u.side==='player'){if(u.y<=57&&u.y>=42)steerBridge(u);u.y-=speed;if(enemies.length===0)u.y-=speed*.65;if(u.y<=6){b.botTower=Math.max(0,(b.botTower||0)-Math.max(18,u.card.atk*.08));u.y=7}}else{u.y+=speed;if(enemies.length===0)u.y+=speed*.6;if(u.y>=88)u.y=88}}
 else{if(u.side==='player'&&u.y<=58&&u.y>=42)steerBridge(u);else{u.x+=(target.x-u.x)*.008;u.y+=(target.y-u.y)*.008}}
 u.element.style.left='calc('+u.x+'% - 27px)';u.element.style.top='calc('+u.y+'% - 27px)';hpbar(u)}
 const set=(id,v,w)=>{const e=document.getElementById(id),bar=document.getElementById(w);if(e)e.textContent=Math.max(0,Math.round(v));if(bar)bar.style.width=Math.max(0,v/10)+'%'};set('botTowerHp',b.botTower||0,'botTowerBar');set('playerTowerHp',b.playerTower||0,'playerTowerBar');const ef=document.getElementById('energyFill');if(ef)ef.style.width=((b.energy||0)/10*100)+'%';const et=document.getElementById('energyText');if(et)et.textContent='Énergie '+(b.energy||0).toFixed(1)+' / 10'}
function boot(){install()}window.addEventListener('load',()=>setTimeout(boot,900));setInterval(boot,1500)})();
