(()=>{'use strict';
let selected=null,run=null,botLast=0,installed=false;
const cards=()=>Array.isArray(window.CARDS)?window.CARDS:[];
const toast=m=>window.toast?window.toast(m):alert(m);
const getCard=id=>cards().find(c=>Number(c.id)===Number(id));
const deck=()=>{let ids=[];try{ids=JSON.parse(localStorage.getItem('crown_rift_deck_v2')||'[]')}catch(e){}if(!Array.isArray(ids))ids=[];return ids.map(getCard).filter(Boolean).slice(0,8)};
function css(){if(document.getElementById('crBattleFix3'))return;const s=document.createElement('style');s.id='crBattleFix3';s.textContent=`#arena.crBattleFix3{background:radial-gradient(circle at 50% 48%,#39285a 0,#17172f 38%,#090d1b 78%);border:2px solid #ffffff18;box-shadow:inset 0 0 100px #000b,0 20px 60px #0008}#arena.crBattleFix3 .crLane{position:absolute;top:0;bottom:0;width:1px;background:#ffffff10;z-index:1}#arena.crBattleFix3 .crLane.l{left:28%}#arena.crBattleFix3 .crLane.r{right:28%}#arena.crBattleFix3 .crBridge{position:absolute;top:45%;height:11%;width:18%;border-radius:10px;background:linear-gradient(180deg,#d9b071,#765033);border:2px solid #ffe4a566;box-shadow:0 7px 20px #0008;z-index:3}.crBridge.a{left:17%}.crBridge.b{right:17%}.crBridge span{display:grid;place-items:center;height:100%;font-size:16px;color:#fff7d0aa}.crBattleFix3 .crRiver{position:absolute;left:0;right:0;top:48%;height:6%;background:linear-gradient(180deg,#183b7b,#49cfff,#183b7b);box-shadow:0 0 28px #35cfff66,inset 0 2px 8px #fff4;z-index:2}.crBattleFix3 .crCenter{position:absolute;left:50%;top:51%;transform:translate(-50%,-50%);width:100px;height:100px;border:1px solid #ffd23f22;border-radius:50%;box-shadow:0 0 35px #8f54ff22;z-index:2}.crBattleFix3 .crChest{position:absolute;left:50%;top:4%;transform:translateX(-50%);font-size:42px;z-index:8;filter:drop-shadow(0 0 18px #ffd23f)}.crBattleFix3 .crDeployHint{position:absolute;left:50%;bottom:3%;transform:translateX(-50%);z-index:30;padding:7px 11px;border-radius:99px;background:#070914cc;border:1px solid #ffffff18;color:#dcd0e7;font-size:9px;white-space:nowrap}.crBattleFix3 .unit{transition:none!important}.crBattleFix3 .unit.crTarget{outline:2px solid #ffd23f;box-shadow:0 0 22px #ffd23f66}.crBattleSelected{outline:3px solid #ffd23f!important;transform:translateY(-5px) scale(1.03);box-shadow:0 0 25px #ffd23f55!important}.crBattleSelected:after{content:'✓ CLIQUE LE TERRAIN';display:block;color:#ffd23f;font-size:7px;font-weight:1000}.crEnergyText{font-size:10px;color:#bdb0ca;text-align:center;margin:4px 0}.crSpawnFx{position:absolute;z-index:25;font-size:28px;pointer-events:none;animation:crSpawn .6s ease-out forwards}@keyframes crSpawn{0%{transform:scale(.2);opacity:0}50%{transform:scale(1.5);opacity:1}100%{transform:scale(2.3);opacity:0}}@media(max-width:700px){.crBattleFix3 .crDeployHint{font-size:8px}.crBattleFix3 .crBridge{width:23%}}`;document.head.appendChild(s)}
function arenaSetup(){const a=document.getElementById('arena');if(!a||a.dataset.crBattle3)return false;a.dataset.crBattle3='1';a.classList.add('crBattleFix3');a.insertAdjacentHTML('beforeend','<div class="crLane l"></div><div class="crLane r"></div><div class="crRiver"></div><div class="crBridge a"><span>✦ PONT ✦</span></div><div class="crBridge b"><span>✦ PONT ✦</span></div><div class="crCenter"></div><div class="crChest">🏆</div><div class="crDeployHint">🃏 Sélectionne une carte en bas → clique dans la zone bleue</div>');a.addEventListener('click',e=>{if(e.target.closest('.deckcard'))return;deploySelected(e)});return true}
function battleActive(){return !!(window.battle&&!window.battle.done&&document.getElementById('arena'))}
function select(id){const c=getCard(id);if(!c||!battleActive())return;if(Number(window.battle.energy||0)<Number(c.cost||1)){toast('Pas assez d’énergie ⚡');return}selected=c;document.querySelectorAll('.deckcard').forEach(x=>{const m=(x.getAttribute('onclick')||'').match(/\d+/);x.classList.toggle('crBattleSelected',Number(m?.[0])===Number(id))});toast('🃏 '+c.name+' sélectionnée — clique dans ta zone bleue');}
function patchGlobal(){window.selectBattleCard=function(id){select(id)};window.crSelectBattleCard=select}
function deploySelected(e){if(!selected||!battleActive())return;const a=document.getElementById('arena'),r=a.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;if(y<57)return toast('❌ Invoque tes cartes dans la zone bleue.');const cost=Number(selected.cost)||1;if(Number(window.battle.energy||0)<cost)return toast('Pas assez d’énergie ⚡');window.battle.energy=Math.max(0,Number(window.battle.energy||0)-cost);add(selected,'player',Math.max(7,Math.min(93,x)),Math.max(62,Math.min(92,y)));selected=null;document.querySelectorAll('.deckcard').forEach(x=>x.classList.remove('crBattleSelected'));}
function unitEl(u){const e=document.createElement('div');e.className='unit '+u.side;e.innerHTML='<div class="uhp"><i></i></div><span>'+((u.card&&u.card.emoji)||'⚔️')+'</span>';return e}
function add(card,side,x,y){const b=window.battle;if(!b)return null;b.units=b.units||[];const live=b.units.filter(u=>u&&u.hp>0);const max=side==='enemy'?4:12;if(live.filter(u=>u.side===side).length>=max)return null;const hp=Math.max(60,Number(card.hp)||200),u={card:{...card},side,x,y,hp,maxHp:hp,attackCd:0,element:null};u.element=unitEl(u);document.getElementById('arena')?.appendChild(u.element);b.units.push(u);pos(u);const a=document.getElementById('arena');if(a){const fx=document.createElement('div');fx.className='crSpawnFx';fx.textContent='✨';fx.style.left=(x-2)+'%';fx.style.top=(y-2)+'%';a.appendChild(fx);setTimeout(()=>fx.remove(),650)}return u}
function pos(u){if(!u.element)return;u.element.style.left='calc('+u.x+'% - 27px)';u.element.style.top='calc('+u.y+'% - 27px)';const hp=u.element.querySelector('.uhp i');if(hp)hp.style.width=Math.max(0,Math.min(100,u.hp/u.maxHp*100))+'%'}
function live(side){return(window.battle?.units||[]).filter(u=>u&&u.hp>0&&u.side===side)}
function nearest(u,side){return live(side).sort((a,b)=>Math.hypot(a.x-u.x,a.y-u.y)-Math.hypot(b.x-u.x,b.y-u.y))[0]}
function bridge(u){return u.x<50?27:73}
function move(u,target,dt){const bx=bridge(u),sp=Math.max(.12,Math.min(1,Number(u.card.speed)||.55))*0.065*dt;if(u.side==='player'&&u.y>55){u.x+=(bx-u.x)*.025*dt;u.y+=u.y>54?-(sp*.9):0;return}if(u.side==='enemy'&&u.y<45){u.x+=(bx-u.x)*.025*dt;u.y+=sp*.9;return}if(u.y>=45&&u.y<=56&&Math.abs(u.x-bx)>2){u.x+=(bx-u.x)*.05*dt;return}if(u.y>=45&&u.y<=56){u.y+=u.side==='player'?-sp:sp;return}const dx=target.x-u.x,dy=target.y-u.y,d=Math.hypot(dx,dy)||1;u.x+=dx/d*sp;u.y+=dy/d*sp}
function hit(u,t,dt){u.attackCd-=dt;if(u.attackCd>0)return;u.attackCd=Math.max(450,Number(u.card.rate)||900);t.hp-=Math.max(8,Number(u.card.atk)||20);t.element?.classList.add('hit');setTimeout(()=>t.element?.classList.remove('hit'),150)}
function clean(){const b=window.battle;if(!b)return;b.units=(b.units||[]).filter(u=>{if(u.hp>0)return true;u.element?.remove();return false})}
function bot(){const b=window.battle;if(!b||b.done)return;const es=live('enemy');if(es.length>=4||Date.now()-botLast<4300)return;const pool=deck().length?deck():cards().slice(0,8);if(!pool.length)return;const c=pool[Math.floor(Math.random()*pool.length)];add(c,'enemy',Math.random()<.5?20+Math.random()*13:67+Math.random()*13,10);botLast=Date.now()}
function loop(){if(!battleActive())return;const b=window.battle;arenaSetup();b.energy=Math.min(10,Number(b.energy||0)+0.035);clean();const all=[...(b.units||[])];for(const u of all){if(!u||u.hp<=0)continue;const enemySide=u.side==='player'?'enemy':'player',t=nearest(u,enemySide);let target=t;if(!target)target={x:50,y:u.side==='player'?4:95};if(t&&Math.hypot(t.x-u.x,t.y-u.y)<13)hit(u,t,1);else move(u,target,1);pos(u)}clean();for(const u of live('player'))if(u.y<7){b.botTower=Math.max(0,(Number(b.botTower)||100)-Math.max(4,Number(u.card.atk||20)*.035));u.y=9;pos(u)}for(const u of live('enemy'))if(u.y>94){b.playerTower=Math.max(0,(Number(b.playerTower)||100)-Math.max(4,Number(u.card.atk||20)*.035));u.y=92;pos(u)}const et=document.getElementById('energyText');if(et)et.textContent='Énergie '+Number(b.energy||0).toFixed(1)+' / 10';const ef=document.getElementById('energyFill');if(ef)ef.style.width=(Number(b.energy||0)/10*100)+'%';bot()}
function install(){if(installed)return;installed=true;patchGlobal();arenaSetup();document.addEventListener('click',e=>{const c=e.target.closest('.deckcard');if(!c)return;const a=document.getElementById('arena');if(!a||!battleActive())return;const id=(c.getAttribute('onclick')||'').match(/\d+/)?.[0]||c.dataset.id;if(id){e.preventDefault();e.stopImmediatePropagation();select(Number(id))}},true);setInterval(()=>{patchGlobal();arenaSetup()},700);}
function watch(){install();if(!run)run=setInterval(loop,100)}window.addEventListener('load',()=>setTimeout(watch,900));setInterval(watch,1200);
})();
