(()=>{'use strict';const starters=[
{id:1,name:'Brise-Fer',rar:'common',type:'Tank',emoji:'🪨',cost:3,atk:34,hp:310,range:34,speed:.55,rate:900,desc:'Mur vivant'},
{id:2,name:'Lance-Aile',rar:'common',type:'Distance',emoji:'🏹',cost:3,atk:46,hp:150,range:95,speed:.62,rate:850,desc:'Tire de loin'},
{id:3,name:'Éclaireur',rar:'common',type:'Assassin',emoji:'🗡️',cost:2,atk:29,hp:115,range:28,speed:1.05,rate:650,desc:'Très vif'},
{id:4,name:'Garde-Roche',rar:'common',type:'Tank',emoji:'🛡️',cost:4,atk:27,hp:430,range:28,speed:.44,rate:1050,desc:'Protection lourde'},
{id:5,name:'Pyromancienne',rar:'uncommon',type:'Distance',emoji:'🔥',cost:4,atk:62,hp:165,range:105,speed:.5,rate:1050,desc:'Braises brûlantes'},
{id:6,name:'Corbeau',rar:'uncommon',type:'Volant',emoji:'🦅',cost:3,atk:57,hp:145,range:70,speed:1,rate:900,desc:'Rapide dans les airs'},
{id:7,name:'Gelombre',rar:'uncommon',type:'Contrôle',emoji:'❄️',cost:3,atk:39,hp:190,range:72,speed:.7,rate:1000,desc:'Ralentit les cibles'},
{id:8,name:'Rôdeur Vert',rar:'uncommon',type:'Distance',emoji:'🌿',cost:2,atk:41,hp:125,range:82,speed:.82,rate:780,desc:'Chasseur discret'}];
const names=['Astre','Braise','Brume','Ronce','Quartz','Foudre','Givre','Sable','Lueur','Ombre','Rune','Corail','Météore','Mousse','Cendre','Éther','Tempête','Cristal','Néant','Aube','Crépuscule','Flamme','Glacier','Vent','Terre','Marée','Roc','Arcane','Sylve','Étoile','Comète','Titan','Spectre','Vortex','Prisme','Orage','Lune','Soleil','Rift','Couronne','Éclipse','Bastion','Venin','Épine','Faucon','Dragon','Oracle','Sentinelle','Chimère','Rôdeur'];
const suffix=['Alpha','Éclat','Gardien','Danseur','Furie','Veilleur'],types=['Tank','Distance','Assassin','Support','Volant','Contrôle','Essaim'],emojis=['🛡️','🏹','🗡️','🔮','🪽','❄️','🦗','🔥','🌑','🌿','⚡','💎','☄️','🌪️','🐉','👑','☠️','🌙','☀️','🌀','🐺','🦊','🧙','🥷','🗿','🧚','🧛','👹','🤖','🦁'];
const rar=['common','uncommon','rare','epic','legendary','mythic','secret'];let cards=[...starters];for(let id=9;id<=300;id++){const n=id-9,i=n%names.length,j=Math.floor(n/names.length),r=rar[Math.min(6,Math.floor((id-9)/42))];cards.push({id,name:names[i]+' '+suffix[j%suffix.length]+' '+(j+1),rar:r,type:types[n%types.length],emoji:emojis[n%emojis.length],cost:2+(n%8),atk:30+(n*17)%360,hp:120+(n*53)%1400,range:32+(n*7)%120,speed:+(.35+((n*13)%75)/100).toFixed(2),rate:650+(n*113)%1050,desc:'Carte du Crown Rift'});}
window.CR_CARDS=cards;window.CR_TOTAL_CARDS=300;})();