(()=>{'use strict';
const C=()=>Array.isArray(window.CARDS)?window.CARDS:[];
const R=()=>window.RARITIES||[{id:'common',name:'Commun',cls:'r-common'},{id:'uncommon',name:'Peu commun',cls:'r-uncommon'},{id:'rare',name:'Rare',cls:'r-rare'},{id:'epic',name:'Épique',cls:'r-epic'},{id:'legendary',name:'Légendaire',cls:'r-legendary'},{id:'mythic',name:'Mythique',cls:'r-mythic'},{id:'secret',name:'Secret',cls:'r-secret'}];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rarity=c=>R().find(x=>x.id===String(c?.rar||c?.rarity))||R()[0];
function getDeck(){let d=[];try{d=JSON.parse(localStorage.getItem('crown_rift_deck_v2')||'null')}catch(e){}if(!Array.isArray(d)||!d.length)d=Array.isArray(window.profile?.deck)?window.profile.deck:[];d=[...new Set(d.map(Number))].filter(id=>C().some(c=>Number(c.id)===id)).slice(0,8);if(!d.length)d=C().slice(0,8).map(c=>Number(c.id));return d}
function saveDeck(d){d=[...new Set(d.map(Number))].filter(id=>C().some(c=>Number(c.id)===id)).slice(0,8);try{localStorage.setItem('crown_rift_deck_v2',JSON.stringify(d))}catch(e){}if(window.profile)window.profile.deck=[...d];if(window.sb&&window.user)window.sb.from('profiles').update({deck:d}).then(q=>{if(q?.error)console.warn('Deck Supabase:',q.error.message)});return d}
function canonicalize(){const d=getDeck();saveDeck(d);return d}
function syncBottomDeck(){const root=document.getElementById('deck');if(!root)return;const ids=canonicalize();const current=[...root.querySelectorAll('.deckcard')];if(current.length!==ids.length)return;const byId=new Map(current.map(el=>[Number(el.dataset.id||String(el.getAttribute('onclick')||'').match(/selectBattleCard\((\d+)\)/)?.[1]||0),el]));let good=true;ids.forEach((id,i)=>{const el=byId.get(id);if(!el)good=false;else if(root.children[i]!==el)root.appendChild(el)});if(!good)renderHand(ids);}
function renderHand(ids){const root=document.getElementById('deck');if(!root)return;root.innerHTML=ids.map(id=>{const c=C().find(x=>Number(x.id)===id);if(!c)return '';return `<button class="deckcard" data-id="${c.id}" onclick="selectBattleCard(${c.id})"><span style="font-size:24px">${esc(c.emoji)}</span><b>${esc(c.name)}</b><small>⚡ ${c.cost} • ⚔️ ${c.atk}</small></button>`}).join('')}
function style(){if(document.getElementById('crIdentityCss'))return;const s=document.createElement('style');s.id='crIdentityCss';s.textContent=`.crIdOverlay{position:fixed;inset:0;z-index:500;display:none;place-items:center;background:#050208e8;padding:18px}.crIdOverlay.show{display:grid}.crIdBox{width:min(520px,100%);padding:22px;border-radius:26px;background:linear-gradient(180deg,#27163a,#0e0815);border:1px solid #ffffff20;box-shadow:0 35px 110px #000}.crIdTop{display:flex;gap:16px;align-items:center}.crIdArt{width:112px;height:112px;border-radius:24px;display:grid;place-items:center;font-size:64px;background:radial-gradient(circle,#ffffff18,transparent 70%);border:1px solid #ffffff18}.crIdName{font-size:27px;font-weight:1000;line-height:1}.crIdRarity{font-size:10px;font-weight:1000;letter-spacing:1.5px;text-transform:uppercase;margin-top:7px}.crIdGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:16px}.crIdStat{padding:11px;border-radius:13px;background:#ffffff08;border:1px solid #ffffff10}.crIdStat span{display:block;color:#ae9eb9;font-size:9px}.crIdStat b{display:block;font-size:16px;margin-top:2px}.crIdSpecial{margin-top:12px;padding:13px;border-radius:14px;background:#ffd23f0d;border:1px solid #ffd23f22;color:#ffd23f}.crIdClose{width:100%;margin-top:15px;padding:13px;border-radius:13px;background:#30203d;font-weight:1000}`;document.head.appendChild(s)}
function identity(c){if(!c)return;style();let m=document.getElementById('crIdentity');if(!m){m=document.createElement('div');m.id='crIdentity';m.className='crIdOverlay';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('show')})}const r=rarity(c),own=Number(window.profile?.owned_cards?.[c.id]||0);m.innerHTML=`<div class="crIdBox"><div class="crIdTop"><div class="crIdArt">${esc(c.emoji)}</div><div><div class="crIdName">${esc(c.name)}</div><div class="crIdRarity ${esc(r.cls)}">${esc(r.name)}</div><div style="color:#ae9eb9;font-size:11px;margin-top:8px">${esc(c.type||'Unité')} • ${esc(c.desc||'Carte de Crown Rift')}</div></div></div><div class="crIdGrid"><div class="crIdStat"><span>⚡ COÛT</span><b>${c.cost}</b></div><div class="crIdStat"><span>⚔️ ATTAQUE</span><b>${c.atk}</b></div><div class="crIdStat"><span>❤️ PV</span><b>${c.hp}</b></div><div class="crIdStat"><span>🎯 PORTÉE</span><b>${c.range}</b></div><div class="crIdStat"><span>💨 VITESSE</span><b>${Number(c.speed||0).toFixed(2)}</b></div><div class="crIdStat"><span>📦 POSSESSION</span><b>x${own}</b></div></div><div class="crIdSpecial">✨ ${esc(c.special||'Pouvoir du Rift')}</div><button class="crIdClose">FERMER</button></div>`;m.querySelector('.crIdClose').onclick=()=>m.classList.remove('show');m.classList.add('show')}
function patchCollection(){document.addEventListener('click',e=>{if(e.target.closest('.crIdOverlay'))return;const el=e.target.closest('#cards .card[data-card-id], .crDeckCard[data-id], .crPick[data-id]');if(!el)return;const id=Number(el.dataset.cardId||el.dataset.id);const c=C().find(x=>Number(x.id)===id);if(!c)return;if(el.closest('#cards .card')||!window.battle) {e.preventDefault();e.stopImmediatePropagation();identity(c)}},true)}
function patchRender(){const old1=window.renderBattleDeck;window.renderBattleDeck=()=>{const ids=canonicalize();if(typeof old1==='function')old1();setTimeout(()=>syncBottomDeck(),0)};const old2=window.renderDeck;window.renderDeck=()=>{if(typeof old2==='function')old2();setTimeout(()=>{canonicalize();syncBottomDeck()},0)}}
function boot(){style();canonicalize();patchRender();patchCollection();syncBottomDeck();setInterval(()=>{canonicalize();syncBottomDeck()},1200)}
window.addEventListener('load',()=>setTimeout(boot,2200));
})();
