(()=>{'use strict';
const A=()=>window.sb||null, P=()=>window.profile||null, U=()=>window.user||null, T=m=>window.toast?window.toast(m):alert(m);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function patchFriends(){
 const btns=[...document.querySelectorAll('button')].filter(b=>/AJOUTER|ajouter/i.test(b.textContent||''));
 btns.forEach(b=>{if(b.dataset.crFriend)return;b.dataset.crFriend='1';b.addEventListener('click',async e=>{const input=document.getElementById('friendName');if(!input)return;e.stopImmediatePropagation();const n=input.value.trim();if(!n)return T('Écris un pseudo.');const s=A(),u=U();if(!s||!u)return T('Connecte-toi d’abord.');const q=await s.from('profiles').select('id,username,display_name').or(`username.ilike.${n},display_name.ilike.${n}`).neq('id',u.id).limit(10);if(q.error)return T('Erreur recherche : '+q.error.message);const target=q.data?.[0];if(!target)return T('Joueur introuvable.');const z=await s.from('friend_requests').insert({sender_id:u.id,receiver_id:target.id,status:'pending'});if(z.error)return T(z.error.code==='23505'?'Demande déjà envoyée.':'Erreur : '+z.error.message);input.value='';T('Demande envoyée à '+(target.display_name||target.username)+' 👑');if(typeof window.loadFriends==='function')window.loadFriends()})})
}
function adminPanel(){
 const mod=[...document.querySelectorAll('.roomModal')].find(x=>/ADMIN CROWN RIFT/i.test(x.textContent||''));if(!mod)return;const panel=mod.querySelector('#adminPanel');if(!panel||panel.style.display==='none'||document.getElementById('crAdminV2'))return;
 const cards=Array.isArray(window.CARDS)?window.CARDS:[];
 const d=document.createElement('div');d.id='crAdminV2';d.className='rp';d.style.marginTop='12px';d.innerHTML=`<h3>👑 ADMIN — RÉCOMPENSES</h3><div style="font-size:11px;color:#ae9eb9;margin-bottom:8px">Entre un pseudo pour récompenser un autre joueur, ou laisse vide pour TON compte.</div><input id="admTarget" class="ri" placeholder="🔎 Rechercher un pseudo..." autocomplete="off"><div id="admTargetList" style="margin:5px 0 10px"></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><input id="admPieces2" class="ri" type="number" min="0" value="1000" placeholder="Pièces"><input id="admGems2" class="ri" type="number" min="0" value="500" placeholder="Gemmes"></div><select id="admCard2" class="ri" style="margin-top:8px"><option value="">Aucune carte</option>${cards.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} — ${esc(c.rarity||c.rar||'')}</option>`).join('')}</select><input id="admQty2" class="ri" type="number" min="1" value="1" placeholder="Quantité"><button id="admGive2" class="rb rgold">✨ AJOUTER LES RÉCOMPENSES</button><div id="admStatus2" style="font-size:10px;color:#ae9eb9;margin-top:7px"></div>`;panel.appendChild(d);
 let target=null;const inp=d.querySelector('#admTarget'),list=d.querySelector('#admTargetList');inp.addEventListener('input',async()=>{target=null;const n=inp.value.trim();if(n.length<2){list.innerHTML='';return}const s=A();if(!s)return;const q=await s.from('profiles').select('id,username,display_name,gems,gold,owned_cards').or(`username.ilike.%${n}%,display_name.ilike.%${n}%`).limit(8);list.innerHTML=(q.data||[]).map(x=>`<button type="button" data-id="${esc(x.id)}" style="display:block;width:100%;text-align:left;margin:3px 0;padding:7px;border-radius:8px;border:1px solid #ffffff15;background:#ffffff08;color:#fff">👤 ${esc(x.display_name||x.username)} <small>${esc(x.username)}</small></button>`).join('');list.querySelectorAll('button').forEach(b=>b.onclick=()=>{target=(q.data||[]).find(x=>x.id===b.dataset.id);inp.value=target?.display_name||target?.username||'';list.innerHTML='Cible : '+esc(inp.value)})});d.querySelector('#admGive2').onclick=async()=>{const s=A(),me=U();if(!s||!me)return T('Connecte-toi d’abord.');const dest=target||P();if(!dest?.id)return T('Pseudo cible introuvable.');const pieces=Math.max(0,parseInt(d.querySelector('#admPieces2').value)||0),gems=Math.max(0,parseInt(d.querySelector('#admGems2').value)||0),cid=d.querySelector('#admCard2').value,qty=Math.max(1,parseInt(d.querySelector('#admQty2').value)||1);const own={...(dest.owned_cards||{})};if(cid)own[cid]=(parseInt(own[cid])||0)+qty;const patch={gold:(parseInt(dest.gold)||0)+pieces,gems:(parseInt(dest.gems)||0)+gems,owned_cards:own};const q=await s.from('profiles').update(patch).eq('id',dest.id);if(q.error)return T('Erreur sauvegarde : '+q.error.message);if(dest.id===me.id){Object.assign(P()||{},patch);if(typeof window.renderAll==='function')window.renderAll()}d.querySelector('#admStatus2').textContent=`✓ ${pieces} pièces • ${gems} gemmes${cid?' • '+qty+' carte(s)':''} → ${dest.display_name||dest.username}`;T('Récompense ajoutée 👑')};
}
function deck(){
 if(document.getElementById('crDeck'))return;const anchor=[...document.querySelectorAll('h2,h3,.section-title')].find(x=>/cartes|collection/i.test(x.textContent||''));if(!anchor)return;const box=document.createElement('div');box.id='crDeck';box.className='panel';box.style.marginTop='12px';box.innerHTML='<h3>🃏 MON DECK — 8 CARTES</h3><div id="crDeckSlots" style="display:grid;grid-template-columns:repeat(4,1fr);gap:6px"></div><div style="font-size:10px;color:#ae9eb9;margin-top:7px">Clique une carte de ta collection pour l’ajouter/retirer du deck.</div>';anchor.parentElement?.appendChild(box);renderDeck();}
function renderDeck(){const box=document.getElementById('crDeckSlots'),p=P();if(!box||!p)return;const deck=Array.isArray(p.deck)?p.deck.map(String):[];const cards=Array.isArray(window.CARDS)?window.CARDS:[];box.innerHTML=Array.from({length:8},(_,i)=>{const c=cards.find(x=>String(x.id)===deck[i]);return `<div style="padding:8px;border-radius:10px;border:1px solid #ffffff15;text-align:center">${c?esc(c.emoji||'🃏')+' '+esc(c.name):'＋ VIDE'}</div>`}).join('');}
function patchDeckClicks(){const p=P();if(!p)return;document.querySelectorAll('[data-card-id],.card-item,.collection-card,.card').forEach(el=>{if(el.dataset.crDeck)return;const id=el.dataset.cardId||el.getAttribute('data-id');if(!id)return;el.dataset.crDeck='1';el.addEventListener('click',()=>{const cards=Array.isArray(window.CARDS)?window.CARDS:[],c=cards.find(x=>String(x.id)===String(id));if(!c)return;const d=Array.isArray(p.deck)?p.deck.map(String):[];const ix=d.indexOf(String(id));if(ix>=0)d.splice(ix,1);else{if(d.length>=8)return T('Ton deck est plein : 8 cartes maximum.');d.push(String(id))}p.deck=d;const s=A(),u=U();if(s&&u)s.from('profiles').update({deck:d}).eq('id',u.id);renderDeck()})})}
function combatFix(){const root=document;const old=window.startTextMatch;if(typeof old==='function'&&!window.__crCombat){window.__crCombat=true;window.startTextMatch=async function(...a){const r=old.apply(this,a);return r}}}
function boot(){patchFriends();adminPanel();deck();patchDeckClicks();combatFix();}
window.addEventListener('load',()=>setTimeout(boot,800));setInterval(boot,1200);window.CROWN_RIFT_FIX={renderDeck,boot};
})();
