(()=>{'use strict';
const S=()=>window.sb,A=()=>window.profile,U=()=>window.user,T=m=>window.toast?window.toast(m):alert(m),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cards=()=>window.CR_CARDS||[];
function own(){const p=A();return p?.owned_cards||{}}
function deckIds(){const p=A(),o=own(),saved=Array.isArray(o.__deck)?o.__deck.map(String):null;if(saved?.length)return saved.slice(0,8);return cards().filter(c=>+o[c.id]>0).slice(0,8).map(c=>String(c.id))}
async function saveOwned(o){const p=A(),s=S(),u=U();if(!p||!s||!u)return false;const q=await s.from('profiles').update({owned_cards:o}).eq('id',u.id);if(q.error){T('Sauvegarde impossible : '+q.error.message);return false}p.owned_cards=o;return true}
async function findPlayer(n){const s=S();if(!s)return null;let q=await s.from('profiles').select('id,username,display_name,gems,gold,owned_cards').ilike('display_name',n).neq('id',U()?.id||'').maybeSingle();if(q.data)return q.data;q=await s.from('profiles').select('id,username,display_name,gems,gold,owned_cards').ilike('username',n+'%').neq('id',U()?.id||'').limit(1);return q.data?.[0]||null}
window.addFriend=async()=>{const input=document.getElementById('friendName'),n=input?.value.trim();if(!n)return T('Entre le pseudo du joueur.');if(n.length<2)return T('Pseudo trop court.');const s=S(),u=U();if(!s||!u)return T('Connecte-toi d’abord.');const target=await findPlayer(n);if(!target)return T('Joueur introuvable.');const q=await s.from('friend_requests').insert({sender_id:u.id,receiver_id:target.id,status:'pending'});if(q.error)return T(q.error.code==='23505'?'Demande déjà envoyée.':q.error.message);input.value='';document.getElementById('friendResult').textContent='✅ Demande envoyée à '+(target.display_name||target.username);T('Ami demandé 👑');if(window.loadFriends)window.loadFriends()};
function style(){if(document.getElementById('crv3style'))return;const st=document.createElement('style');st.id='crv3style';st.textContent=`#crv3deck{padding:15px;border-radius:18px;background:#12091a;border:1px solid #ffffff15;margin-top:10px}.crv3grid{display:grid;grid-template-columns:repeat(5,1fr);gap:9px}.crv3c{padding:9px;border-radius:15px;background:#1a1025;border:1px solid #ffffff14;color:white;text-align:left;cursor:pointer}.crv3c.sel{outline:2px solid #ffd23f;background:#2b1a37}.crv3c.lock{opacity:.35;filter:grayscale(1)}.crv3c .pic{height:72px;display:grid;place-items:center;font-size:39px}.crv3slots{display:grid;grid-template-columns:repeat(8,1fr);gap:7px;margin:8px 0}.crv3slot{padding:9px 5px;border-radius:11px;background:#09060e;border:1px solid #ffffff14;text-align:center;font-size:9px}.crv3slot.sel{outline:2px solid #ffd23f}.crv3search{width:100%;padding:12px;border-radius:10px;background:#09060e;color:#fff;border:1px solid #ffffff19}.crv3suggest{padding:7px;border-radius:9px;background:#ffffff08;border:1px solid #ffffff12;margin-top:4px;cursor:pointer}.crv3chest{position:absolute;top:18px;left:calc(50% - 28px);width:56px;height:52px;border-radius:15px;display:grid;place-items:center;font-size:31px;background:linear-gradient(#ffd65b,#8c4913);border:2px solid #fff5;z-index:8;box-shadow:0 0 28px #ffd23f55}@media(max-width:900px){.crv3grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:650px){.crv3grid{grid-template-columns:repeat(2,1fr)}.crv3slots{grid-template-columns:repeat(4,1fr)}}`;document.head.appendChild(st)}
function renderDeckView(){let box=document.getElementById('crv3deck');if(!box){const page=document.getElementById('cards');if(!page)return;box=document.createElement('div');box.id='crv3deck';box.style.display='none';page.appendChild(box)}const o=own(),ids=deckIds(),set=new Set(ids);box.innerHTML=`<div class="title" style="margin-top:0"><div><h2>🃏 MON DECK</h2><span>Choisis exactement 8 cartes</span></div><button class="btn gold" id="crv3auto">8 STARTERS</button></div><div class="crv3slots">${Array.from({length:8},(_,i)=>{const c=cards().find(x=>String(x.id)===ids[i]);return `<div class="crv3slot ${c?'sel':''}">${c?c.emoji+'<br>'+E(c.name):'＋ VIDE'}</div>`}).join('')}</div><div class="muted" style="font-size:11px;margin-bottom:8px">Clique une carte pour l'ajouter ou la retirer. Les 8 cartes choisies sont utilisées en combat.</div><div class="crv3grid">${cards().map(c=>{const ok=+o[c.id]>0||c.id<=8,sel=set.has(String(c.id));return `<button class="crv3c ${ok?'':'lock'} ${sel?'sel':''}" data-crvid="${c.id}" ${ok?'':'disabled'}><div class="pic">${c.emoji}</div><b>${E(c.name)}</b><small>${E(c.type)} · ⚔️${c.atk} · ❤️${c.hp}</small></button>`}).join('')}</div>`;box.querySelectorAll('[data-crvid]').forEach(b=>b.onclick=()=>toggleDeck(b.dataset.crvid));box.querySelector('#crv3auto').onclick=()=>{const p=A(),o={...(p.owned_cards||{})};o.__deck=[1,2,3,4,5,6,7,8];saveOwned(o).then(renderDeckView)}
}
async function toggleDeck(id){const p=A(),o={...(p?.owned_cards||{})},ids=deckIds();const i=ids.findIndex(x=>x===String(id));if(i>=0)ids.splice(i,1);else{if(ids.length>=8)return T('Le deck est déjà plein : 8 cartes.');ids.push(String(id))}o.__deck=ids;if(await saveOwned(o))renderDeckView()}
const oldSet=window.setCardTab;window.setCardTab=function(t){if(t==='deck'){['cardsCollection','cardsFusion','cardsPacks'].forEach(id=>document.getElementById(id)?.classList.add('hidden'));document.getElementById('crv3deck').style.display='block';document.querySelectorAll('#cards .tab').forEach(x=>x.classList.remove('on'));document.getElementById('crv3deckTab')?.classList.add('on');renderDeckView();return}if(window.oldSetCardTab&&t)window.oldSetCardTab(t);else if(typeof oldSet==='function')oldSet(t);if(t==='collection')renderCollection()};window.oldSetCardTab=oldSet;
function renderCollection(){const grid=document.getElementById('collectionGrid'),o=own();if(!grid)return;document.getElementById('totalCards').textContent='300';grid.innerHTML=cards().map(c=>{const n=+o[c.id]||0;return `<div class="card ${n?'':'lock'}"><div class="cardtop"><span class="energy">${c.cost}</span><span class="rar">${c.rar}</span></div><div class="art">${c.emoji}</div><h3>${E(c.name)}</h3><div class="sub">${E(c.type)} · ${E(c.desc)}</div><div class="cstats"><div class="pill">⚔️ ${c.atk}</div><div class="pill">❤️ ${c.hp}</div></div>${n?`<span class="owned">x${n}</span>`:''}</div>`}).join('')}
async function pack300(pack){const costs={standard:50,elite:120,crown:250},cost=costs[pack]||50,p=A();if(!p||(+p.gems||0)<cost)return T('Pas assez de gemmes 💎');const o={...(p.owned_cards||{})},draw=[];for(let i=0;i<5;i++){const c=cards()[Math.floor(Math.random()*cards().length)];draw.push(c);o[c.id]=(o[c.id]||0)+1}o.__deck=deckIds();if(!(await saveOwned(o)))return;await window.saveProfile?.({gems:(+p.gems||0)-cost});T('Pack ouvert : '+draw.map(x=>x.name).join(', '));renderCollection();renderDeckView()}
function cardTabs(){const tabs=document.querySelector('#cards .tabs');if(!tabs||document.getElementById('crv3deckTab'))return;const b=document.createElement('button');b.id='crv3deckTab';b.className='tab';b.textContent='🃏 DECK';b.onclick=()=>setCardTab('deck');tabs.appendChild(b);renderDeckView();}
function admin(){const panel=document.getElementById('adminPanel');if(!panel||panel.style.display==='none'||document.getElementById('crv3admin'))return;const d=document.createElement('div');d.id='crv3admin';d.className='rp';const list=cards();d.innerHTML=`<h3>🎁 RÉCOMPENSER UN JOUEUR</h3><input id="crv3target" class="ri" placeholder="🔎 Pseudo du joueur"><div id="crv3find"></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:7px"><input id="crv3g" class="ri" type="number" value="500" min="0" placeholder="Gemmes"><input id="crv3gold" class="ri" type="number" value="1000" min="0" placeholder="Pièces"></div><select id="crv3card" class="ri"><option value="">Aucune carte</option>${list.map(c=>`<option value="${c.id}">${E(c.name)} — ${c.rar}</option>`).join('')}</select><input id="crv3qty" class="ri" type="number" min="1" value="1"><button id="crv3give" class="rb rgold">✨ AJOUTER</button><div id="crv3msg" class="muted" style="font-size:10px"></div>`;panel.appendChild(d);let target=null;const inp=d.querySelector('#crv3target'),res=d.querySelector('#crv3find');inp.oninput=async()=>{const q=await findPlayer(inp.value.trim());target=q;res.innerHTML=q?`<div class="crv3suggest">👤 ${E(q.display_name||q.username)}</div>`:inp.value.length>1?'Aucun joueur':''};d.querySelector('#crv3give').onclick=async()=>{const me=U(),s=S();if(!me||!s)return T('Connecte-toi d’abord.');const dest=target||A();if(!dest?.id)return T('Choisis un joueur.');const o={...(dest.owned_cards||{})},g=+d.querySelector('#crv3g').value||0,go=+d.querySelector('#crv3gold').value||0,cid=d.querySelector('#crv3card').value,q=Math.max(1,+d.querySelector('#crv3qty').value||1);if(cid)o[cid]=(o[cid]||0)+q;const z=await s.from('profiles').update({gems:(+dest.gems||0)+g,gold:(+dest.gold||0)+go,owned_cards:o}).eq('id',dest.id);if(z.error)return T(z.error.message);d.querySelector('#crv3msg').textContent='✅ Récompenses ajoutées à '+(dest.display_name||dest.username);if(dest.id===me.id){Object.assign(A(),{gems:(+dest.gems||0)+g,gold:(+dest.gold||0)+go,owned_cards:o});window.renderAll?.()}}}
function chat(){const i=document.getElementById('chatInput'),b=document.getElementById('sendChat');if(!i||!b)return;i.disabled=false;i.readOnly=false;i.style.pointerEvents='auto';i.style.userSelect='text';if(!i.dataset.crv3){i.dataset.crv3='1';i.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();b.click()}}}}
let fight=null;
function unit(c,side,x,y){const arena=document.getElementById('arena'),id='crv3u'+Math.random().toString(36).slice(2);const e=document.createElement('div');e.className='unit '+side;e.dataset.id=id;e.innerHTML=`<div class="uhp"><i style="width:100%"></i></div><span>${c.emoji}</span>`;e.style.left=`${x}%`;e.style.top=`${y}%`;arena.appendChild(e);return{id,e,c,side,x,y,hp:c.hp,cd:0}}
function startFight(){if(!window.page)return;page('battle');document.getElementById('battleLobby')?.classList.add('hidden');document.getElementById('battleGame')?.classList.remove('hidden');const ar=document.getElementById('arena');if(!ar)return;ar.querySelectorAll('.crv3chest,.unit,.damage').forEach(e=>e.remove());const chest=document.createElement('div');chest.className='crv3chest';chest.textContent='🏆';ar.appendChild(chest);fight={on:true,energy:10,player:[],enemy:[],last:Date.now(),chestDmg:0,started:Date.now()};renderBattleDeck();T('Combat lancé ⚔️')}
function renderBattleDeck(){const box=document.getElementById('deck');if(!box)return;const set=deckIds().map(id=>cards().find(c=>String(c.id)===id)).filter(Boolean);box.innerHTML=set.map(c=>`<button class="deckcard" data-bid="${c.id}"><span style="font-size:24px">${c.emoji}</span><b>${E(c.name)}</b><small>⚡${c.cost} · ⚔️${c.atk}</small></button>`).join('');box.querySelectorAll('[data-bid]').forEach(b=>b.onclick=()=>{fight&&fight.selected=cards().find(c=>c.id==b.dataset.bid);T('Carte sélectionnée : '+fight.selected.name)})}
function deployPlayer(){if(!fight?.selected)return T('Choisis une carte dans ton deck.');const c=fight.selected;if(fight.energy<c.cost)return T('Pas assez d’énergie.');fight.energy-=c.cost;fight.player.push(unit(c,'player',35+Math.random()*30,80+Math.random()*8))}
function deployEnemy(){if(!fight?.on)return;const c=cards().filter(c=>c.id>8)[Math.floor(Math.random()*(cards().length-8))];if(fight.enemy.length<8)fight.enemy.push(unit(c,'enemy',35+Math.random()*30,18+Math.random()*8))}
function nearest(u,list){return list.filter(x=>x.hp>0).sort((a,b)=>Math.hypot(a.x-u.x,a.y-u.y)-Math.hypot(b.x-u.x,b.y-u.y))[0]}
function kill(u){u.hp=0;u.e.remove()}
function tick(){if(!fight?.on)return;fight.energy=Math.min(10,fight.energy+.04);const now=Date.now();if(now-fight.started>120000){fight.on=false;return}for(const u of [...fight.player,...fight.enemy]){if(u.hp<=0)continue;u.cd-=90;const enemies=u.side==='player'?fight.enemy:fight.player,t=nearest(u,enemies);if(t&&Math.hypot(t.x-u.x,t.y-u.y)<12){if(u.cd<=0){t.hp=Math.max(0,t.hp-u.c.atk);u.cd=u.c.rate;if(t.hp<=0)kill(t)}}else if(u.side==='enemy'){if(fight.player.some(x=>x.hp>0)){u.y+=u.c.speed*.08}else{u.y-=u.c.speed*.08;if(u.y<10){fight.chestDmg=Math.min(999,fight.chestDmg+u.c.atk*.002);u.hp=Math.max(1,u.hp);u.y=10}}}else{if(fight.enemy.some(x=>x.hp>0))u.y-=u.c.speed*.08;else u.y-=u.c.speed*.08;if(u.y<8){document.getElementById('botTowerHp').textContent=Math.max(0,(+document.getElementById('botTowerHp').textContent||1000)-u.c.atk*.02);kill(u)}}u.e.style.left=u.x+'%';u.e.style.top=u.y+'%';u.e.querySelector('.uhp i').style.width=Math.max(0,u.hp/u.c.hp*100)+'%'};fight.player=fight.player.filter(x=>x.hp>0);fight.enemy=fight.enemy.filter(x=>x.hp>0);}
function boot(){style();cardTabs();renderCollection();renderDeckView();admin();chat();document.getElementById('arena')?.addEventListener('click',e=>{if(!fight)return;const r=e.currentTarget.getBoundingClientRect(),y=(e.clientY-r.top)/r.height*100;if(y>55)deployPlayer()});if(typeof window.startBotBattle==='function')window.startBotBattle=startFight;setInterval(()=>{if(fight?.on){if(Math.random()<.025)deployEnemy();tick()}},100);}
window.addEventListener('load',()=>setTimeout(boot,700));setInterval(boot,1400);window.CROWN_RIFT_V3={cards,deckIds,startFight};})();