(()=>{'use strict';
const KEY='crown_rift_deck_v2';
const C=()=>Array.isArray(window.CARDS)?window.CARDS:[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cardOf=id=>C().find(c=>Number(c.id)===Number(id));
const rarityList=()=>Array.isArray(window.RARITIES)&&window.RARITIES.length?window.RARITIES:[{id:'common',weight:58},{id:'uncommon',weight:23},{id:'rare',weight:11},{id:'epic',weight:5},{id:'legendary',weight:2},{id:'mythic',weight:.8},{id:'secret',weight:.2}];
const getIds=()=>{let d=[];try{d=JSON.parse(localStorage.getItem(KEY)||'[]')}catch(e){}if(!Array.isArray(d))d=[];const owned=window.profile?.owned_cards||{};d=d.map(Number).filter(id=>cardOf(id)&&Number(owned[id]||0)>0);if(!d.length){d=C().filter(c=>Number(owned[c.id]||0)>0).slice(0,8).map(c=>Number(c.id))}return [...new Set(d)].slice(0,8)};
function login300(){document.querySelectorAll('.authgrid .mini span,.authgrid .mini p').forEach(x=>{x.textContent=x.textContent.replace(/21\s*cartes?/gi,'300 cartes')});document.querySelectorAll('#totalCards').forEach(x=>x.textContent='300');document.querySelectorAll('.homegrid .tile p').forEach(x=>{x.textContent=x.textContent.replace(/21\s*cartes?/gi,'300 cartes')})}
function ownedColors(){const owned=window.profile?.owned_cards||{};document.querySelectorAll('#collectionGrid .card[data-card-id]').forEach(el=>{const id=Number(el.dataset.cardId),yes=Number(owned[id]||0)>0;el.classList.toggle('lock',!yes);el.classList.toggle('crOwned',yes);el.style.filter=yes?'none':'grayscale(1) brightness(.62)';el.style.opacity=yes?'1':'.52'});if(!document.getElementById('crOwnedCardsStyle')){const s=document.createElement('style');s.id='crOwnedCardsStyle';s.textContent=`#collectionGrid .card.crOwned{filter:none!important;opacity:1!important;background:linear-gradient(180deg,#35204f,#140b1d)!important;border-color:#ffffff28!important;box-shadow:0 10px 30px #0009,0 0 18px #8f54ff18!important}#collectionGrid .card.lock{filter:grayscale(1) brightness(.62)!important;opacity:.52!important}`;document.head.appendChild(s)}}
let lockedHandHTML='';
function handHTML(ids){return ids.map(id=>{const c=cardOf(id);return c?`<button class="deckcard" data-id="${c.id}" onclick="selectBattleCard(${c.id})"><span style="font-size:24px">${esc(c.emoji)}</span><b>${esc(c.name)}</b><small>⚡ ${c.cost} • ⚔️ ${c.atk}</small></button>`:''}).join('')}
function battleActive(){return !!(window.battle&&!window.battle.done&&document.getElementById('battleGame')&&!document.getElementById('battleGame').classList.contains('hidden'))}
function stabilizeDeck(){const root=document.getElementById('deck');if(!root)return;if(!battleActive()){lockedHandHTML='';return}const ids=getIds();const html=handHTML(ids);if(html!==lockedHandHTML||root.innerHTML!==html){lockedHandHTML=html;root.innerHTML=html}}
function stopDeckOscillation(){const root=document.getElementById('deck');if(!root||root.dataset.crFinalObserver)return;root.dataset.crFinalObserver='1';const obs=new MutationObserver(()=>{if(battleActive())stabilizeDeck()});obs.observe(root,{childList:true,subtree:true});window.CR_FINAL_DECK_OBSERVER=obs}
function speedAndPath(){const b=window.battle;if(!b||b.done)return;const units=Array.isArray(b.units)?b.units:[];for(const u of units){if(!u||u.hp<=0)continue;const enemies=units.filter(v=>v&&v.hp>0&&v.side!==u.side);let t=enemies.sort((a,z)=>Math.hypot(a.x-u.x,a.y-u.y)-Math.hypot(z.x-u.x,z.y-u.y))[0];if(t&&Math.hypot(t.x-u.x,t.y-u.y)<10)continue;if(!t)t={x:50,y:u.side==='player'?4:95};const dx=t.x-u.x,dy=t.y-u.y,d=Math.hypot(dx,dy)||1;const base=Math.max(.28,Number(u.card?.speed)||.55);const mult=u.side==='player'?1.35:0.72;const step=base*.08*mult;u.x+=dx/d*step;u.y+=dy/d*step;u.x=Math.max(5,Math.min(95,u.x));u.y=Math.max(4,Math.min(96,u.y));if(u.element){u.element.style.left='calc('+u.x+'% - 27px)';u.element.style.top='calc('+u.y+'% - 27px)'}u._crFast=1}}
function specialButton(){document.querySelectorAll('.crIdSpecial').forEach(el=>{if(el.dataset.finalSpecial)return;el.dataset.finalSpecial='1';el.style.cursor='pointer';el.title='Voir toutes les informations';el.addEventListener('click',e=>{e.preventDefault();e.stopPropagation()})})}
function patchCollectionIdentity(){if(document.getElementById('crFinalUxCss'))return;const s=document.createElement('style');s.id='crFinalUxCss';s.textContent=`.crIdSpecial{cursor:pointer!important;user-select:none}.crIdSpecial:hover{box-shadow:0 0 0 1px #ffd23f44,0 0 22px #ffd23f18;transform:translateY(-1px);transition:.15s}.deck{grid-template-columns:repeat(8,1fr)}#deck .deckcard{min-width:0;overflow:hidden}#deck .deckcard b{white-space:nowrap;text-overflow:ellipsis;overflow:hidden}.crSpecialButton{display:block}`;document.head.appendChild(s)}
function weightedRarity(){const rs=rarityList(),total=rs.reduce((a,r)=>a+Number(r.weight||0),0),n=Math.random()*total;let x=n;for(const r of rs){x-=Number(r.weight||0);if(x<=0)return r.id}return rs[0].id}
async function finalOpenPack(pack){const costs={standard:50,elite:120,crown:250},cost=costs[pack]||50,p=window.profile;if(!p||!window.sb||!window.user)return window.toast&&window.toast('Connecte-toi d’abord.');if(Number(p.gems||0)<cost)return window.toast&&window.toast('Pas assez de gemmes 💎');const owned={...(p.owned_cards||{})};const draw=[];for(let i=0;i<5;i++){const rar=weightedRarity(),pool=C().filter(c=>c.rar===rar),c=pool.length?pool[Math.floor(Math.random()*pool.length)]:C()[Math.floor(Math.random()*C().length)];if(!c)continue;draw.push(c);owned[c.id]=(Number(owned[c.id]||0)+1)}const save={gems:Number(p.gems||0)-cost,owned_cards:owned,gold:Number(p.gold||0)+draw.filter(c=>Number(p.owned_cards?.[c.id]||0)>0).length*18};if(typeof window.saveProfile==='function'){if(!await window.saveProfile(save))return}else{p.gems=save.gems;p.owned_cards=save.owned_cards;p.gold=save.gold}const modal=document.getElementById('modal'),title=document.getElementById('modalTitle'),body=document.getElementById('modalBody');if(!modal||!title||!body)return;title.textContent='📦 OUVERTURE DU PACK';body.innerHTML='<div style="padding:30px;text-align:center;font-size:20px;font-weight:1000;color:#ffd23f">✨ Le Rift révèle 5 cartes…</div>';modal.classList.add('show');await new Promise(r=>setTimeout(r,650));title.textContent='🎁 5 CARTES DU RIFT';body.innerHTML='<p class="muted">Les doublons rapportent 18 🪙 chacun.</p><div class="reveal">'+draw.map(c=>`<div class="card" style="animation:crPackReveal .45s ease both"><div class="cardtop"><span class="energy">${c.cost}</span><span class="rar r-${esc(c.rar)}">${esc((rarityList().find(r=>r.id===c.rar)||{}).name||c.rar)}</span></div><div class="art">${esc(c.emoji)}</div><h3>${esc(c.name)}</h3><div class="sub">${esc(c.type||'Unité')} • ${esc(c.desc||'Carte du Crown Rift')}</div><div class="cstats"><div class="pill">⚔️ ${c.atk}</div><div class="pill">❤️ ${c.hp}</div><div class="pill">🎯 ${c.range}</div><div class="pill">💨 ${Number(c.speed||0).toFixed(2)}</div></div></div>`).join('')+'</div>';if(!document.getElementById('crPackRevealStyle')){const s=document.createElement('style');s.id='crPackRevealStyle';s.textContent='@keyframes crPackReveal{from{opacity:0;transform:translateY(14px) scale(.9) rotateY(50deg)}to{opacity:1;transform:none}}';document.head.appendChild(s)}}
function installPack(){window.openPack=finalOpenPack}
function boot(){login300();ownedColors();patchCollectionIdentity();stopDeckOscillation();stabilizeDeck();specialButton();installPack();setInterval(()=>{login300();ownedColors();stopDeckOscillation();stabilizeDeck();specialButton();installPack();speedAndPath()},180)}
window.addEventListener('load',()=>setTimeout(boot,3200));setTimeout(()=>{try{boot()}catch(e){}},4200);
})();
