(()=>{'use strict';
const C=()=>Array.isArray(window.CARDS)?window.CARDS:[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cardOf=id=>C().find(c=>Number(c.id)===Number(id));
function specialInfo(c){const name=c?.special||'Pouvoir du Rift', cost=Number(c?.specialCost||c?.cost||2), cd=Number(c?.specialCd||7000);const desc={"Frappe royale":"Frappe massive qui inflige de gros dégâts à la cible la plus proche.","Explosion du Rift":"Explosion autour de l’unité qui touche plusieurs ennemis.","Charge éclair":"L’unité fonce rapidement vers sa cible et augmente ses dégâts.","Bouclier ancestral":"Réduit les dégâts reçus pendant quelques secondes.","Météore":"Un météore tombe sur la zone ciblée et inflige des dégâts de zone.","Pluie de plumes":"Une pluie de projectiles frappe plusieurs ennemis.","Gel absolu":"Immobilise brièvement la cible et inflige des dégâts.","Flèche toxique":"Projectile empoisonné qui inflige des dégâts supplémentaires.","Lame astrale":"Attaque rapide qui frappe fortement la cible.","Soin du Rift":"Restaure une partie des PV de l’unité alliée.","Exécution":"Inflige des dégâts supplémentaires aux ennemis déjà affaiblis.","Nuée sauvage":"Invoque une nuée qui attaque rapidement la cible.","Impact solaire":"Impact lumineux avec dégâts de zone.","Rappel des ombres":"Téléportation courte suivie d’une attaque surprise.","Souffle de cendres":"Souffle à distance qui brûle les ennemis.","Brume meurtrière":"Crée une zone qui inflige des dégâts progressivement.","Lune écrasée":"Puissante attaque verticale avec dégâts de zone.","Rayon d’éclipse":"Rayon concentré qui traverse les ennemis.","Frappe du Néant":"Frappe extrêmement puissante contre une cible.","Renaissance":"Restaure une partie des PV après un délai.","Colère du Wyrm":"Attaque dévastatrice du Wyrm touchant une large zone."}[name]||'Une attaque spéciale unique du Crown Rift.');return {name,cost,cd,desc,damage:Math.round(Number(c?.atk||30)*(1.15+cost*.08)),target:'Ennemis dans la portée de la carte',effect:'Effet spécial propre à cette carte',duration:Math.round(cd/1000)+' s de recharge'} }
function css(){if(document.getElementById('crUX2'))return;const s=document.createElement('style');s.id='crUX2';s.textContent=`#crBattleInfo{margin:7px 0;padding:7px 10px;border-radius:10px;background:#0a0711;border:1px solid #ffffff12;color:#ae9eb9;font-size:9px;text-align:center}#crSpecialInfo{margin-top:13px;padding:14px;border-radius:16px;background:#ffd23f0a;border:1px solid #ffd23f24}.crSIgrid{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin-top:10px}.crSI{padding:9px;border-radius:11px;background:#ffffff08}.crSI span{display:block;color:#ae9eb9;font-size:8px}.crSI b{display:block;font-size:12px;margin-top:2px}.crSpecialButton{cursor:pointer;color:#ffd23f}.crSpecialButton:hover{text-decoration:underline}@media(max-width:700px){.crSIgrid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function specialModal(c){css();let m=document.getElementById('crSpecialModal');if(!m){m=document.createElement('div');m.className='crIdOverlay';m.id='crSpecialModal';m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('show')});document.body.appendChild(m)}const s=specialInfo(c);m.innerHTML=`<div class="crIdBox"><div class="crIdTop"><div class="crIdArt">${esc(c.emoji)}</div><div><div class="crIdName">✨ ${esc(s.name)}</div><div class="crIdRarity">ATTAQUE SPÉCIALE</div><div style="color:#ae9eb9;font-size:11px;margin-top:8px">${esc(c.name)}</div></div></div><div id="crSpecialInfo"><div style="font-size:14px;font-weight:1000;color:#ffd23f">${esc(s.desc)}</div><div class="crSIgrid"><div class="crSI"><span>⚡ COÛT</span><b>${s.cost}</b></div><div class="crSI"><span>💥 DÉGÂTS</span><b>${s.damage}</b></div><div class="crSI"><span>🎯 CIBLE</span><b>${esc(s.target)}</b></div><div class="crSI"><span>⏱️ RECHARGE</span><b>${s.duration}</b></div><div class="crSI"><span>🌀 EFFET</span><b>${esc(s.effect)}</b></div><div class="crSI"><span>📊 FORMULE</span><b>ATK × multiplicateur</b></div></div></div><button class="crIdClose">FERMER</button></div>`;m.querySelector('.crIdClose').onclick=()=>m.classList.remove('show');m.classList.add('show')}
function addSpecialButton(){document.querySelectorAll('.crIdSpecial').forEach(el=>{if(el.dataset.sp)return;el.dataset.sp='1';const text=el.textContent.trim().replace(/^✨\s*/,'');el.innerHTML=`<span class="crSpecialButton">✨ ${esc(text)} — CLIQUER POUR LES INFOS</span>`;el.onclick=()=>{const box=el.closest('.crIdBox');const name=(box?.querySelector('.crIdName')?.textContent||'').replace('✨ ','').trim();const c=C().find(x=>x.name===name);if(c)specialModal(c)}})}
function patchHand(){const root=document.getElementById('deck');if(!root)return;const arena=document.getElementById('arena');const active=!!(window.battle&&!window.battle.done&&arena);if(!active)return;const ids=[];try{const d=JSON.parse(localStorage.getItem('crown_rift_deck_v2')||'[]');if(Array.isArray(d))d.slice(0,8).forEach(x=>ids.push(Number(x)))}catch(e){}if(!ids.length)return;const existing=[...root.querySelectorAll('.deckcard')];if(existing.length===ids.length&&existing.every((el,i)=>Number(el.dataset.id||0)===ids[i]))return;root.innerHTML=ids.map(id=>{const c=cardOf(id);return c?`<button class="deckcard" data-id="${c.id}" onclick="selectBattleCard(${c.id})"><span style="font-size:24px">${esc(c.emoji)}</span><b>${esc(c.name)}</b><small>⚡ ${c.cost} • ⚔️ ${c.atk}</small></button>`:''}).join('')}
function speedUnits(){const b=window.battle;if(!b||b.done)return;for(const u of b.units||[]){if(!u||u.hp<=0)continue;u._crFast=1.85}}
function fixMovement(){const b=window.battle;if(!b||b.done)return;for(const u of b.units||[]){if(!u||u.hp<=0)continue;const enemies=(b.units||[]).filter(v=>v&&v.hp>0&&v.side!==u.side);const t=enemies.sort((a,z)=>Math.hypot(a.x-u.x,a.y-u.y)-Math.hypot(z.x-u.x,z.y-u.y))[0];const target=t||{x:50,y:u.side==='player'?5:95};const dx=target.x-u.x,dy=target.y-u.y,d=Math.hypot(dx,dy)||1;const sp=(Number(u.card?.speed)||.55)*.11*(u._crFast||1.85);if(t&&d<14){continue}u.x+=dx/d*sp;u.y+=dy/d*sp;u.x=Math.max(5,Math.min(95,u.x));u.y=Math.max(4,Math.min(96,u.y));if(u.element){u.element.style.left='calc('+u.x+'% - 27px)';u.element.style.top='calc('+u.y+'% - 27px)'}}}
function boot(){css();setInterval(()=>{patchHand();addSpecialButton();speedUnits();fixMovement()},250)}window.addEventListener('load',()=>setTimeout(boot,2500));
})();