(()=>{'use strict';
if(window.__CR_PACK_BATTLE_FIX__)return;window.__CR_PACK_BATTLE_FIX__=true;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const allCards=()=>Array.isArray(window.CARDS)&&window.CARDS.length?window.CARDS:(window.CR_CARDS||[]);
const owned=id=>Number(window.profile?.owned_cards?.[id]||0);
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
let packBusy=false,packCard=null,packStep=0,packCost=0;
let hand=[],handReady=false,replaceTimer=null;
function css(){if(document.getElementById('crPackBattleCss'))return;const s=document.createElement('style');s.id='crPackBattleCss';s.textContent=`
#crPackReveal{position:fixed;inset:0;z-index:5000;display:none;place-items:center;background:#030207ee;padding:18px}.crprBox{width:min(520px,100%);text-align:center;padding:24px;border-radius:28px;background:radial-gradient(circle at 50% 15%,#633b8c,#180b24 55%,#09050f);border:1px solid #ffffff25;box-shadow:0 30px 100px #000}.crprHint{margin:13px 0;color:#cbbbd4;font-size:12px}.crprPack{width:190px;height:250px;margin:10px auto 18px;border-radius:24px;display:grid;place-items:center;background:linear-gradient(145deg,#ffb62e,#9b3dff 55%,#35165b);border:4px solid #ffd23f;box-shadow:0 0 35px #ffd23f55,0 20px 40px #0009;cursor:pointer;font-size:80px;transition:.25s}.crprPack:hover{transform:scale(1.04) rotate(-1deg)}.crprCard{width:220px;min-height:310px;margin:10px auto 18px;padding:13px;border-radius:22px;background:linear-gradient(180deg,#302044,#100815);border:3px solid #ffd23f;box-shadow:0 0 35px #ffd23f44,0 25px 45px #0009;cursor:pointer}.crprArt{height:145px;border-radius:17px;display:grid;place-items:center;background:radial-gradient(circle,#ffffff22,transparent 70%);font-size:82px}.crprCard h2{font-size:20px;margin:9px 0 4px}.crprCard p{margin:4px;color:#bcaec7;font-size:10px}.crprReceive{width:100%;padding:14px;border-radius:14px;background:linear-gradient(135deg,#ff9b18,#ffd846);color:#241000;font-weight:1000}.crprHidden{display:none!important}
#deck.crFiveHand{grid-template-columns:repeat(5,minmax(0,1fr))}.crFiveCard{min-height:96px;padding:7px;border-radius:15px;text-align:left;background:linear-gradient(180deg,#241533,#120a18);border:1px solid #ffffff18;color:#fff;transition:.14s;position:relative;cursor:pointer}.crFiveCard:hover{transform:translateY(-3px)}.crFiveCard.selected{outline:3px solid #ffd23f;box-shadow:0 0 26px #ffd23f44;transform:translateY(-5px)}.crFiveCard b{display:block;font-size:9px;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.crFiveCard small{display:block;color:#bcb0c6;font-size:8px;margin-top:2px}.crFiveArt{height:49px;border-radius:10px;display:grid;place-items:center;background:radial-gradient(circle,#ffffff18,transparent 70%);font-size:28px}.crHandTimer{position:absolute;right:5px;top:5px;background:#ffd23f;color:#241000;border-radius:99px;padding:3px 5px;font-size:7px;font-weight:1000}.crHandLocked{opacity:.55;pointer-events:none}
@media(max-width:900px){#deck.crFiveHand{grid-template-columns:repeat(5,minmax(0,1fr));gap:4px}.crFiveCard{min-height:75px;padding:4px}.crFiveArt{height:36px;font-size:21px}.crFiveCard b{font-size:7px}.crFiveCard small{font-size:6px}}
`;document.head.appendChild(s)}
function profileGems(){return Number(window.profile?.gems??0)}
async function saveProfilePatch(patch){if(window.profile)Object.assign(window.profile,patch);if(window.sb&&window.user)await window.sb.from('profiles').update(patch).eq('id',window.user.id)}
function randomPackCard(){const a=allCards();if(!a.length)return null;return a[Math.floor(Math.random()*a.length)]}
function addOwned(c){const oc={...(window.profile?.owned_cards||{})};oc[c.id]=Number(oc[c.id]||0)+1;return oc}
function packModal(){let m=document.getElementById('crPackReveal');if(!m){m=document.createElement('div');m.id='crPackReveal';document.body.appendChild(m)}return m}
async function finishPack(){if(!packCard)return;const oc=addOwned(packCard);await saveProfilePatch({owned_cards:oc});window.profile.owned_cards=oc;packBusy=false;const m=packModal();m.innerHTML=`<div class="crprBox"><div style="font-size:11px;color:#ffd23f;font-weight:1000;letter-spacing:2px">CARTE OBTENUE</div><div class="crprCard" style="cursor:default"> <div class="crprArt">${esc(packCard.emoji)}</div><h2>${esc(packCard.name)}</h2><p>${esc(packCard.type||'Unité')} • ${esc(packCard.rar||'common')}</p><p>⚔️ ${packCard.atk} &nbsp; ❤️ ${packCard.hp}</p></div><button class="crprReceive">RECEVOIR ✓</button></div>`;m.querySelector('.crprReceive').onclick=()=>{m.style.display='none';packCard=null;packStep=0;document.querySelectorAll('[data-pack-refresh]').forEach(x=>x.click())};}
function openPackSequence(cost){if(packBusy)return;if(profileGems()<cost){if(typeof window.toast==='function')window.toast('Pas assez de gemmes 💎');return}packBusy=true;packCost=cost;packCard=randomPackCard();if(!packCard){packBusy=false;return}saveProfilePatch({gems:profileGems()-cost});const m=packModal();m.style.display='grid';packStep=0;m.innerHTML=`<div class="crprBox"><div style="font-size:12px;color:#ffd23f;font-weight:1000;letter-spacing:2px">PACK CROWN RIFT</div><div class="crprPack">🎁</div><div class="crprHint">Clique sur le pack pour l'ouvrir.</div></div>`;m.querySelector('.crprPack').onclick=()=>{if(packStep!==0)return;packStep=1;m.querySelector('.crprPack').outerHTML=`<div class="crprPack" style="background:linear-gradient(145deg,#fff4b0,#ffd23f 30%,#8f54ff);font-size:74px">🃏</div>`;m.querySelector('.crprHint').textContent='Clique encore pour révéler la carte.';m.querySelector('.crprPack').onclick=()=>{if(packStep!==1)return;packStep=2;m.querySelector('.crprPack').outerHTML=`<div class="crprCard"><div class="crprArt">${esc(packCard.emoji)}</div><h2>${esc(packCard.name)}</h2><p>${esc(packCard.rar||'common')} • ${esc(packCard.type||'Unité')}</p></div>`;m.querySelector('.crprHint').textContent='Clique sur la carte pour voir ses détails.';m.querySelector('.crprCard').onclick=async()=>{if(packStep!==2)return;packStep=3;await finishPack()}}}};
function installPackClicks(){document.addEventListener('click',e=>{if(packBusy)return;const b=e.target.closest('.pack button,.pack [data-buy-pack],.pack [data-pack-buy]');if(!b)return;const pack=b.closest('.pack');if(!pack)return;e.preventDefault();e.stopImmediatePropagation();const raw=b.dataset.cost||pack.dataset.cost||pack.querySelector('.price')?.textContent||'0';const nums=String(raw).replace(/\s/g,'').match(/\d+/g);const cost=nums?Number(nums[nums.length-1]):0;if(cost<=0){if(typeof window.toast==='function')window.toast('Prix du pack introuvable.');return}openPackSequence(cost)},true)}
function deckSource(){let d=Array.isArray(window.profile?.deck)?window.profile.deck:[];if(!d.length){try{d=JSON.parse(localStorage.getItem('crown_rift_deck_v3')||localStorage.getItem('crown_rift_deck_v2')||'[]')}catch(e){d=[]}}return [...new Set(d.map(Number))].map(id=>allCards().find(c=>Number(c.id)===id)).filter(Boolean).slice(0,8)}
function pickHand(){const pool=deckSource();if(pool.length<=5)return pool.slice();const a=pool.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a.slice(0,5)}
function renderFive(){const d=document.getElementById('deck');if(!d)return;d.classList.add('crFiveHand');d.innerHTML=hand.map(c=>`<button class="crFiveCard" data-cr-hand-id="${c.id}"><div class="crFiveArt">${esc(c.emoji)}</div><b>${esc(c.name)}</b><small>⚡ ${c.cost} • ⚔️ ${c.atk}</small></button>`).join('');d.querySelectorAll('.crFiveCard').forEach(el=>el.onclick=()=>playHandCard(Number(el.dataset.crHandId),el));}
function playHandCard(id,el){if(replaceTimer)return;const c=hand.find(x=>Number(x.id)===id);if(!c)return;document.querySelectorAll('.crFiveCard').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');if(typeof window.selectBattleCard==='function'){try{window.selectBattleCard(id)}catch(e){try{window.selectBattleCard(c)}catch(_){}}}else{const old=[...document.querySelectorAll('#deck .deckcard,[data-card-id]')].find(x=>Number(x.dataset.cardId||x.dataset.id)===id);if(old&&old!==el)old.click()}let left=3;el.insertAdjacentHTML('beforeend',`<span class="crHandTimer">3</span>`);const t=setInterval(()=>{left--;const q=el.querySelector('.crHandTimer');if(q)q.textContent=String(left);if(left<=0){clearInterval(t);replaceHandCard(id)}},1000);replaceTimer=t}
function replaceHandCard(id){replaceTimer=null;const pool=deckSource().filter(c=>!hand.some(x=>Number(x.id)===Number(c.id)));if(pool.length){const n=pool[Math.floor(Math.random()*pool.length)];hand=hand.filter(c=>Number(c.id)!==Number(id));hand.push(n)}else{hand=pickHand()}renderFive()}
function ensureHand(){const d=document.getElementById('deck');if(!d)return;if(!handReady){hand=pickHand();handReady=true;renderFive();return}if(d.children.length!==5||!d.classList.contains('crFiveHand'))renderFive()}
function watchBattle(){const d=document.getElementById('deck');if(!d)return;ensureHand();if(!window.__CR_HAND_OBS__){const mo=new MutationObserver(()=>{if(!replaceTimer)ensureHand()});mo.observe(d,{childList:true,subtree:true});window.__CR_HAND_OBS__=mo}if(!window.__CR_FAST_SPEED__){window.__CR_FAST_SPEED__=true;const st=document.createElement('style');st.textContent='.crUnit2,.unit{transition:left .045s linear,top .045s linear!important}';document.head.appendChild(st)}}
function startWatcher(){css();installPackClicks();setInterval(()=>{const arena=document.getElementById('arena');if(arena&&arena.offsetParent!==null)watchBattle()},500)}
window.addEventListener('load',()=>setTimeout(startWatcher,500));setTimeout(startWatcher,1200);
})();
