(()=>{
'use strict';
const ADMIN='HaalandTheBest';
let ch=null,code='',pc=null,stream=null,duel=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=m=>window.toast?window.toast(m):alert(m);
const css=`#roomsBtn,#adminBtn{position:fixed;bottom:18px;z-index:180;border:0;border-radius:18px;padding:13px 16px;color:#fff;font-weight:1000;cursor:pointer;box-shadow:0 12px 35px #0009}#roomsBtn{right:18px;background:linear-gradient(135deg,#ff9b00,#ff3d82,#8f54ff)}#adminBtn{left:18px;background:#24152f}.roomModal{position:fixed;inset:0;z-index:300;display:none;place-items:center;background:#050208dd;padding:14px}.roomModal.show{display:grid}.roomBox{width:min(950px,100%);max-height:92vh;overflow:auto;padding:20px;border-radius:25px;background:linear-gradient(180deg,#1b1027,#0c0712);border:1px solid #ffffff20;color:#fff;box-shadow:0 25px 90px #000}.rg{display:grid;grid-template-columns:1fr 1fr;gap:12px}.rp{padding:16px;border-radius:18px;background:#ffffff07;border:1px solid #ffffff14}.ri{width:100%;padding:12px;border-radius:11px;background:#09060e;color:#fff;border:1px solid #ffffff18;margin:5px 0}.rb{padding:11px 14px;border:0;border-radius:11px;background:#2b1c39;color:#fff;font-weight:950;cursor:pointer;margin:4px}.rgold{background:linear-gradient(135deg,#ff9700,#ffd644);color:#210e00}.rgreen{background:linear-gradient(135deg,#0ca86b,#4fe4a0)}.rpink{background:linear-gradient(135deg,#ff397e,#934cff)}.rred{background:#451722;color:#ff9dac}.rhead{display:flex;justify-content:space-between;align-items:center}.rhead h2{margin:0}.rcode{text-align:center;font-size:34px;letter-spacing:7px;color:#ffd34b;font-weight:1000;padding:12px}.rchat{height:220px;overflow:auto;background:#08050d;border-radius:13px;padding:10px}.rmsg{font-size:12px;margin:7px 0}.rmsg b{color:#ffd34b}.users{display:flex;gap:6px;flex-wrap:wrap}.userpill{padding:7px 10px;border-radius:99px;background:#171020;border:1px solid #ffffff15;font-size:11px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.rCard{padding:9px;border-radius:13px;background:#171020;color:#fff;border:1px solid #ffffff15;text-align:left;cursor:pointer}.rCard.sel{outline:2px solid #ffd34b}.rCard span{font-size:25px}.rCard b,.rCard small{display:block}.rCard b{font-size:10px}.rCard small{font-size:9px;color:#aa9bb8}.rh{height:11px;background:#08050d;border-radius:99px;overflow:hidden;margin:6px 0}.rh i{display:block;height:100%;background:linear-gradient(90deg,#4fe5a2,#ffd34b,#ff4f6d)}@media(max-width:700px){.rg{grid-template-columns:1fr}.cards{grid-template-columns:repeat(2,1fr)}}`;
function add(tag,html,attrs={}){const e=document.createElement(tag);e.innerHTML=html;for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e}
function build(){if(document.getElementById('roomsBtn'))return;document.head.appendChild(add('style',css));const room=add('div',`<div class="roomBox"><div class="rhead"><h2>🎙️ SALON SOCIAL</h2><button class="rb" id="rx">✕</button></div><div id="rh"><div class="rg"><div class="rp"><h3>Créer une room</h3><input id="rn" class="ri" placeholder="Nom de la room"><button id="rc" class="rb rgold">🚀 CRÉER</button></div><div class="rp"><h3>Rejoindre</h3><input id="jc" class="ri" maxlength="6" placeholder="CODE"><button id="join" class="rb rgreen">🚪 REJOINDRE</button></div></div></div><div id="riw" style="display:none"><div class="rg"><div class="rp"><div>CODE DE ROOM</div><div id="rcode" class="rcode"></div><div id="users" class="users"></div><button id="voice" class="rb rgreen">🎙️ ACTIVER LA VOIX</button><button id="leave" class="rb rred">QUITTER</button><button id="startD" class="rb rpink">⚔️ LANCER LE 1V1</button></div><div class="rp"><h3>💬 Chat</h3><div id="chatBox" class="rchat"></div><input id="chatInput" class="ri" placeholder="Message"><button id="sendChat" class="rb rgold">ENVOYER</button></div></div><div id="duelBox" class="rp" style="display:none;margin-top:12px"><h3>⚔️ RIFT DUEL 1V1</h3><div id="duelStatus">Choisis ta carte.</div><div id="duelCards" class="cards"></div><div class="rg"><div><b id="meName">TOI</b><div class="rh"><i id="meHp" style="width:100%"></i></div><span id="meHpText">1000 HP</span></div><div><b id="enemyName">ADVERSAIRE</b><div class="rh"><i id="enemyHp" style="width:100%"></i></div><span id="enemyHpText">1000 HP</span></div></div><button id="attack" class="rb rpink" disabled>⚔️ ATTAQUER</button></div></div></div>`);room.className='roomModal';document.body.appendChild(room);const admin=add('div',`<div class="roomBox"><div class="rhead"><h2>👑 ADMIN CROWN RIFT</h2><button class="rb" id="adminClose">✕</button></div><div id="adminAuth"><input id="adminPass" class="ri" type="password" placeholder="Mot de passe admin"><button id="adminLogin" class="rb rgold">ACCÉDER</button></div><div id="adminPanel" style="display:none"><div class="rp"><h3>Gestion des joueurs</h3><div id="adminUsers"></div></div></div></div>`);admin.className='roomModal';document.body.appendChild(admin);
const $=id=>document.getElementById(id);$('roomsBtn')||document.body.appendChild(add('button','🎙️ SALON SOCIAL',{id:'roomsBtn'}));$('adminBtn')||document.body.appendChild(add('button','👑 ADMIN',{id:'adminBtn'}));
$('roomsBtn').onclick=()=>{if(!window.user||!window.sb)return toast('Connecte-toi d’abord.');room.classList.add('show')};$('adminBtn').onclick=()=>admin.classList.add('show');$('rx').onclick=closeRoom;$('rc').onclick=()=>enter(($('rn').value||'Salon du Rift').slice(0,24),true);$('join').onclick=()=>{const c=$('jc').value.trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(c))return toast('Code invalide');code=c;enter('Salon du Rift',false)};$('leave').onclick=closeRoom;$('sendChat').onclick=sendChat;$('chatInput').onkeydown=e=>e.key==='Enter'&&sendChat();$('voice').onclick=startVoice;$('startD').onclick=startDuel;$('attack').onclick=attack;$('adminClose').onclick=()=>admin.classList.remove('show');$('adminLogin').onclick=adminLogin}
function send(event,payload){if(ch)ch.send({type:'broadcast',event,payload})}
async function enter(name,host){const $=id=>document.getElementById(id);code=host?Math.random().toString(36).slice(2,8).toUpperCase():code;if(ch)await sb.removeChannel(ch);ch=sb.channel('crown-room:'+code);ch.on('broadcast',{event:'chat'},x=>showChat(x.payload));ch.on('broadcast',{event:'hello'},x=>addUser(x.payload));ch.on('broadcast',{event:'voice'},x=>signal(x.payload));ch.on('broadcast',{event:'duel'},x=>duelMessage(x.payload));ch.on('presence',{event:'sync'},renderUsers);await new Promise((ok,no)=>ch.subscribe(s=>{if(s==='SUBSCRIBED')ok();if(s==='CHANNEL_ERROR')no()}));await ch.track({id:user.id,name:profile?.display_name||profile?.username||'Joueur'});$('rh').style.display='none';$('riw').style.display='block';$('rcode').textContent=code;renderUsers();send('hello',{id:user.id,name:profile?.display_name||profile?.username||'Joueur'});showChat({system:true,text:'Room '+name+' • code '+code})}
function addUser(x){const u=document.getElementById('users');if(!u||!x)return;const id='user-'+x.id;if(document.getElementById(id))return;u.insertAdjacentHTML('beforeend',`<div class="userpill" id="${id}">🟢 ${esc(x.name||'Joueur')}</div>`)}
function renderUsers(){const u=document.getElementById('users');if(!u||!ch)return;u.innerHTML='';Object.values(ch.presenceState()).flat().forEach(addUser)}
function showChat(p){const b=document.getElementById('chatBox');if(!b)return;const d=document.createElement('div');d.className='rmsg';d.innerHTML=p.system?esc(p.text):`<b>${esc(p.name||'Joueur')} :</b> ${esc(p.text||'')}`;b.appendChild(d);b.scrollTop=b.scrollHeight}
function sendChat(){const i=document.getElementById('chatInput'),t=i.value.trim();if(!t)return;i.value='';send('chat',{name:profile?.display_name||'Joueur',text:t});showChat({name:profile?.display_name||'Joueur',text:t})}
async function startVoice(){try{stream=await navigator.mediaDevices.getUserMedia({audio:true});if(!pc){pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});stream.getTracks().forEach(t=>pc.addTrack(t,stream));pc.onicecandidate=e=>e.candidate&&send('voice',{type:'ice',candidate:e.candidate});pc.ontrack=e=>{let a=document.getElementById('remoteAudio');if(!a){a=document.createElement('audio');a.id='remoteAudio';a.autoplay=true;document.body.appendChild(a)}a.srcObject=e.streams[0]};const offer=await pc.createOffer();await pc.setLocalDescription(offer);send('voice',{type:'offer',sdp:offer})}document.getElementById('voice').disabled=true;toast('Micro activé 🎙️')}catch(e){toast('Microphone indisponible ou refusé.')}}
async function signal(p){if(p.type==='offer'){if(!pc){await startVoice()}if(pc){await pc.setRemoteDescription(p.sdp);const a=await pc.createAnswer();await pc.setLocalDescription(a);send('voice',{type:'answer',sdp:a})}}else if(p.type==='answer'&&pc)await pc.setRemoteDescription(p.sdp);else if(p.type==='ice'&&pc)try{await pc.addIceCandidate(p.candidate)}catch(e){}}
async function closeRoom(){if(ch)await sb.removeChannel(ch);if(stream)stream.getTracks().forEach(t=>t.stop());if(pc)pc.close();ch=null;pc=null;stream=null;duel=null;document.getElementById('riw').style.display='none';document.getElementById('rh').style.display='block';document.getElementById('users').innerHTML='';document.getElementById('chatBox').innerHTML='';document.getElementById('duelBox').style.display='none'}
function startDuel(){duel={me:null,enemy:null,mhp:1000,ehp:1000,on:false};document.getElementById('duelBox').style.display='block';const list=typeof selectedDeck==='function'?selectedDeck():[];document.getElementById('duelCards').innerHTML=list.slice(0,4).map(c=>`<button class="rCard" data-id="${c.id}"><span>${c.emoji}</span><b>${esc(c.name)}</b><small>⚔️ ${c.atk}</small></button>`).join('');document.querySelectorAll('#duelCards .rCard').forEach(b=>b.onclick=()=>selectCard(+b.dataset.id));send('duel',{type:'start',from:user.id})}
function selectCard(id){const c=CARDS.find(x=>x.id===id);if(!c||!duel)return;duel.me=c;document.querySelectorAll('#duelCards .rCard').forEach(b=>b.classList.toggle('sel',+b.dataset.id===id));send('duel',{type:'select',from:user.id,card:{id:c.id,name:c.name,emoji:c.emoji,atk:c.atk}});ready()}
function ready(){if(duel.me&&duel.enemy){duel.on=true;document.getElementById('attack').disabled=false;document.getElementById('duelStatus').textContent='⚔️ COMBAT !';updateDuel()}}
function duelMessage(p){if(!p||p.from===user.id)return;if(p.type==='start'){if(!duel)startDuel()}else if(p.type==='select'){if(!duel)startDuel();duel.enemy=p.card;document.getElementById('enemyName').textContent=p.card.name;ready()}else if(p.type==='hit'&&duel){duel.mhp=Math.max(0,duel.mhp-p.damage);updateDuel();if(duel.mhp<=0){duel.on=false;document.getElementById('attack').disabled=true;document.getElementById('duelStatus').textContent='💀 DÉFAITE'}}}
function attack(){if(!duel?.on)return;const damage=Math.max(10,Math.round(duel.me.atk*.8));duel.ehp=Math.max(0,duel.ehp-damage);send('duel',{type:'hit',from:user.id,damage});updateDuel();if(duel.ehp<=0){duel.on=false;document.getElementById('attack').disabled=true;document.getElementById('duelStatus').textContent='🏆 VICTOIRE !';toast('Victoire 1V1 👑')}}
function updateDuel(){const $=id=>document.getElementById(id);$('meHp').style.width=duel.mhp/10+'%';$('enemyHp').style.width=duel.ehp/10+'%';$('meHpText').textContent=Math.round(duel.mhp)+' HP';$('enemyHpText').textContent=Math.round(duel.ehp)+' HP'}
async function adminLogin(){if(document.getElementById('adminPass').value!==ADMIN)return toast('Mot de passe admin incorrect.');document.getElementById('adminAuth').style.display='none';document.getElementById('adminPanel').style.display='block';const q=await sb.from('profiles').select('id,username,display_name,gems,gold').limit(100);if(q.error)return toast(q.error.message);document.getElementById('adminUsers').innerHTML=(q.data||[]).map(p=>`<div class="userpill" style="display:flex;justify-content:space-between;width:100%;margin:4px 0"><span>${esc(p.display_name||p.username)} • 💎${p.gems||0} 🪙${p.gold||0}</span><span><button class="rb rgold" onclick="crGift('${p.id}','gems')">+💎100</button><button class="rb rgreen" onclick="crGift('${p.id}','gold')">+🪙100</button></span></div>`).join('')}
window.crGift=async(id,type)=>{const q=await sb.from('profiles').select('gems,gold').eq('id',id).single();if(q.error)return toast(q.error.message);const patch=type==='gems'?{gems:(q.data.gems||0)+100}:{gold:(q.data.gold||0)+100};const r=await sb.from('profiles').update(patch).eq('id',id);toast(r.error?r.error.message:'Récompense donnée 👑');if(!r.error)adminLogin()};
window.addEventListener('load',build);
})();