-- CROWN RIFT — DATABASE SUPABASE
-- À exécuter UNE FOIS dans Supabase > SQL Editor.
-- Le site utilise uniquement la clé anon publique côté navigateur.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  display_name text not null default 'Joueur',
  gems integer not null default 150,
  gold integer not null default 0,
  trophies integer not null default 0,
  xp integer not null default 0,
  level integer not null default 1,
  streak integer not null default 0,
  wins integer not null default 0,
  losses integer not null default 0,
  best_streak integer not null default 0,
  owned_cards jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.friend_requests (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check(status in ('pending','accepted','rejected')),
  created_at timestamptz not null default now(),
  unique(sender_id,receiver_id)
);

create table if not exists public.friendships (
  user_id uuid not null references public.profiles(id) on delete cascade,
  friend_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id,friend_id),
  constraint no_self_friend check(user_id<>friend_id)
);

create table if not exists public.matches (
  id uuid primary key default gen_random_uuid(),
  host_id uuid not null references public.profiles(id) on delete cascade,
  guest_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'invited' check(status in ('invited','ready','playing','finished')),
  state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check(host_id<>guest_id)
);

alter table public.profiles enable row level security;
alter table public.friend_requests enable row level security;
alter table public.friendships enable row level security;
alter table public.matches enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated using (true);
drop policy if exists profiles_insert on public.profiles;
create policy profiles_insert on public.profiles for insert to authenticated with check(id=auth.uid());
drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());

drop policy if exists requests_select on public.friend_requests;
create policy requests_select on public.friend_requests for select to authenticated using(sender_id=auth.uid() or receiver_id=auth.uid());
drop policy if exists requests_insert on public.friend_requests;
create policy requests_insert on public.friend_requests for insert to authenticated with check(sender_id=auth.uid());
drop policy if exists requests_update on public.friend_requests;
create policy requests_update on public.friend_requests for update to authenticated using(receiver_id=auth.uid()) with check(receiver_id=auth.uid());

drop policy if exists friendships_select on public.friendships;
create policy friendships_select on public.friendships for select to authenticated using(user_id=auth.uid());
drop policy if exists friendships_insert on public.friendships;
create policy friendships_insert on public.friendships for insert to authenticated with check(user_id=auth.uid());
drop policy if exists friendships_delete on public.friendships;
create policy friendships_delete on public.friendships for delete to authenticated using(user_id=auth.uid());

drop policy if exists matches_select on public.matches;
create policy matches_select on public.matches for select to authenticated using(host_id=auth.uid() or guest_id=auth.uid());
drop policy if exists matches_insert on public.matches;
create policy matches_insert on public.matches for insert to authenticated with check(host_id=auth.uid());
drop policy if exists matches_update on public.matches;
create policy matches_update on public.matches for update to authenticated using(host_id=auth.uid() or guest_id=auth.uid()) with check(host_id=auth.uid() or guest_id=auth.uid());

grant select,insert,update on public.profiles to authenticated;
grant select,insert,update on public.friend_requests to authenticated;
grant select,insert,delete on public.friendships to authenticated;
grant select,insert,update on public.matches to authenticated;

-- Quand le destinataire accepte, on crée automatiquement l'amitié dans les deux sens.
create or replace function public.make_friend_pair() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  if new.status='accepted' then
    insert into public.friendships(user_id,friend_id) values(new.receiver_id,new.sender_id) on conflict do nothing;
    insert into public.friendships(user_id,friend_id) values(new.sender_id,new.receiver_id) on conflict do nothing;
  end if;
  return new;
end;$$;
drop trigger if exists friend_pair_trigger on public.friend_requests;
create trigger friend_pair_trigger after update of status on public.friend_requests for each row execute function public.make_friend_pair();

-- Supabase Realtime pour les invitations/duels.
alter publication supabase_realtime add table public.matches;
alter publication supabase_realtime add table public.friend_requests;
