(()=>{'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const C=()=>Array.isArray(window.CARDS)?window.CARDS:[];
const R=()=>Array.isArray(window.RARITIES)?window.RARITIES:([{id:'common',name:'Commun',cls:'r-common'},{id:'uncommon',name:'Peu commun',cls:'r-uncommon'},{id:'rare',name:'Rare',cls:'r-rare'},{id:'epic',name:'Épique',cls:'r-epic'},{id:'legendary',name:'Légendaire',cls:'r-legendary'},{id:'mythic',name:'Mythique',cls:'r-mythic'},{id:'secret',name:'Secret',cls:'r-secret'}]);
function rarity(id){return R().find(x=>x.id===id)||R()[0]}
function owned(c){const o=window.profile?.owned_cards||{};return Number(o[c.id]||0)}
function renderCards300(){const grid=document.getElementById('collectionGrid'),filters=document.getElementById('rarityFilters');if(!grid||!filters)return;const current=window.CROWN_CARD_FILTER||'all';const fs=[['all','Toutes'],...R().map(r=>[r.id,r.name])];filters.innerHTML=fs.map(f=>`<button class="${current===f[0]?'on':''}" data-r="${f[0]}">${f[1]}</button>`).join('');filters.querySelectorAll('button').forEach(b=>b.onclick=()=>{window.CROWN_CARD_FILTER=b.dataset.r;renderCards300()});const list=C().filter(c=>current==='all'||c.rar===current);grid.innerHTML=list.map(c=>{const o=owned(c),r=rarity(c.rar);return `<div class="card ${o?'':'lock'}" data-card-id="${c.id}" style="cursor:pointer"><div class="cardtop"><span class="energy">${c.cost}</span><span class="rar ${r.cls}">${r.name}</span></div><div class="art">${esc(c.emoji)}</div><h3>${esc(c.name)}</h3><div class="sub">${esc(c.type)} • ${esc(c.desc)}</div><div class="cstats"><div class="pill">⚔️ ${c.atk}</div><div class="pill">❤️ ${c.hp}</div><div class="pill">🎯 ${c.range}</div><div class="pill">💨 ${Number(c.speed).toFixed(2)}</div></div>${o?`<span class="owned">x${o}</span>`:''}</div>`}).join('');document.getElementById('totalCards')?.replaceChildren(document.createTextNode(String(C().length)));document.querySelectorAll('#cards .card[data-card-id]').forEach(el=>{if(el.dataset.crDeckSelect)return;el.dataset.crDeckSelect='1';el.addEventListener('click',()=>{if(window.CROWN_RIFT_DECK_SELECT)window.CROWN_RIFT_DECK_SELECT(Number(el.dataset.cardId));else document.getElementById('crDeckTab')?.click()})})}
function buildDeckTab(){const page=document.getElementById('cards'),tabs=page?.querySelector('.tabs');if(!page||!tabs||document.getElementById('crDeckTab2'))return;const b=document.createElement('button');b.id='crDeckTab2';b.className='tab';b.textContent='🃏 DECK';tabs.appendChild(b);const panel=document.createElement('div');panel.id='crDeckPanel2';panel.style.display='none';panel.className='panel glass';panel.innerHTML='<div class="title" style="margin-top:0"><div><h2>🃏 MON DECK</h2><span>Choisis exactement 8 cartes parmi ta collection.</span></div><b id="crDeckCount2" style="color:#ffd23f">0 / 8</b></div><div id="crDeckSelected2" class="crDeckSlots"></div><div class="muted" style="font-size:11px;margin:10px 0">Clique sur une carte de la collection pour l’ajouter ou la retirer.</div><div id="crDeckCollection2" class="crDeckGrid"></div>';page.appendChild(panel);b.onclick=()=>{const show=panel.style.display!=='block';panel.style.display=show?'block':'none';b.classList.toggle('on',show);document.getElementById('cardsCollection').style.display=show?'none':'';document.getElementById('cardsFusion').style.display='none';document.getElementById('cardsPacks').style.display='none';if(show)renderDeckPanel()};window.CROWN_RIFT_DECK_SELECT=id=>toggleDeck(id);}
function deckIds(){const p=window.profile||{};let d=Array.isArray(p.deck)?p.deck.map(Number):[];try{const l=JSON.parse(localStorage.getItem('crown_rift_deck_v2')||'[]');if(!d.length&&Array.isArray(l))d=l.map(Number)}catch(e){}return [...new Set(d)].filter(id=>C().some(c=>c.id===id)).slice(0,8)}
function saveDeck(d){window.profile.deck=d;try{localStorage.setItem('crown_rift_deck_v2',JSON.stringify(d))}catch(e){}if(window.sb&&window.user)window.sb.from('profiles').update({deck:d}).eq('id',window.user.id)}
function toggleDeck(id){const d=deckIds(),i=d.indexOf(id);if(i>=0)d.splice(i,1);else{if(d.length>=8)return window.toast?window.toast('Ton deck est plein : 8 cartes maximum.'):null;d.push(id)}saveDeck(d);renderDeckPanel();renderBattleDeck()}
function renderDeckPanel(){const grid=document.getElementById('crDeckCollection2'),sel=document.getElementById('crDeckSelected2');if(!grid||!sel)return;const d=deckIds(),set=new Set(d),own=window.profile?.owned_cards||{};sel.innerHTML=Array.from({length:8},(_,i)=>{const c=C().find(x=>x.id===d[i]);return `<div class="crSlot"><b>${i+1}</b> ${c?esc(c.name):'＋ VIDE'}</div>`}).join('');document.getElementById('crDeckCount2').textContent=d.length+' / 8';grid.innerHTML=C().filter(c=>(own[c.id]||0)>0).map(c=>`<button class="crDeckCard ${set.has(c.id)?'sel':''}" data-id="${c.id}"><div class="art">${esc(c.emoji)}</div><b>${esc(c.name)}</b><small>⚔️ ${c.atk} · ${esc(rarity(c.rar).name)}</small>${set.has(c.id)?'<span class="crDeckBadge">DECK</span>':''}</button>`).join('');grid.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>toggleDeck(Number(b.dataset.id)))}
function renderBattleDeck(){const root=document.getElementById('deck');if(!root)return;const d=deckIds().map(id=>C().find(c=>c.id===id)).filter(Boolean);root.innerHTML=d.map(c=>`<button class="deckcard" onclick="selectBattleCard(${c.id})"><span style="font-size:24px">${esc(c.emoji)}</span><b>${esc(c.name)}</b><small>⚡ ${c.cost} • ⚔️ ${c.atk}</small></button>`).join('');}
function boot(){window.RARITIES=window.RARITIES||[{id:'common',name:'Commun',cls:'r-common'},{id:'uncommon',name:'Peu commun',cls:'r-uncommon'},{id:'rare',name:'Rare',cls:'r-rare'},{id:'epic',name:'Épique',cls:'r-epic'},{id:'legendary',name:'Légendaire',cls:'r-legendary'},{id:'mythic',name:'Mythique',cls:'r-mythic'},{id:'secret',name:'Secret',cls:'r-secret'}];buildDeckTab();window.renderCards=renderCards300;renderCards300();renderDeckPanel();renderBattleDeck()}
window.addEventListener('load',()=>setTimeout(boot,1000));setInterval(()=>{if(window.profile){renderDeckPanel();renderBattleDeck()}},1800);window.CROWN_RIFT_DECK=()=>deckIds().map(id=>C().find(c=>c.id===id)).filter(Boolean);
})();
