(()=>{'use strict';
const toast=m=>window.toast?window.toast(m):alert(m);
const CARDS=()=>Array.isArray(window.CARDS)?window.CARDS:[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const owned=c=>Number((window.profile?.owned_cards||{})[c.id]||0)>0;
function deck(){let d=[];try{d=JSON.parse(localStorage.getItem('crown_rift_deck_v2')||'[]')}catch(e){}if(!Array.isArray(d))d=[];d=d.map(Number).filter(id=>CARDS().some(c=>c.id===id&&owned(c)));const out=[];for(const id of d)if(!out.includes(id))out.push(id);for(const c of CARDS())if(out.length<8&&owned(c)&&!out.includes(c.id))out.push(c.id);return out.slice(0,8)}
async function saveDeck(d){d=d.slice(0,8);localStorage.setItem('crown_rift_deck_v2',JSON.stringify(d));if(window.profile)window.profile.deck=d;if(window.sb&&window.user){const q=await window.sb.from('profiles').update({deck:d}).eq('id',window.user.id);if(q.error)toast('Erreur sauvegarde du deck : '+q.error.message)}if(typeof window.renderAll==='function')window.renderAll()}
function css(){if(document.getElementById('crUltimateCss'))return;const s=document.createElement('style');s.id='crUltimateCss';s.textContent=`#crDeckModal{position:fixed;inset:0;z-index:999;background:#050208ed;display:none;place-items:center;padding:12px}#crDeckModal.on{display:grid}.crUM{width:min(1050px,100%);max-height:92vh;overflow:auto;padding:20px;border-radius:24px;background:linear-gradient(180deg,#241234,#0d0712);border:1px solid #ffffff22;box-shadow:0 30px 100px #000}.crUG{display:grid;grid-template-columns:repeat(5,1fr);gap:9px;margin-top:12px}.crUC{padding:10px;border-radius:16px;text-align:left;background:#151020;border:1px solid #ffffff15;position:relative}.crUC.sel{outline:2px solid #ffd23f;background:#261a36}.crUC .e{font-size:40px;text-align:center}.crUC b{display:block;font-size:10px}.crUC small{color:#ae9eb9;font-size:9px}.crBadge{position:absolute;right:6px;top:6px;color:#66ffb0;font-size:8px;font-weight:1000}.crBack{background:#302039!important}.crPackFX{min-height:410px;display:grid;place-items:center;position:relative;text-align:center;overflow:hidden;background:radial-gradient(circle,#4a185c55,transparent 52%)}.crPackFX:before,.crPackFX:after{content:"";position:absolute;width:280px;height:280px;border-radius:50%;border:2px solid #ffd23f66;animation:crSpin 2.2s linear infinite}.crPackFX:after{width:185px;height:185px;border-color:#8f54ff88;animation-direction:reverse;animation-duration:1.35s}.crCore{font-size:112px;filter:drop-shadow(0 0 35px #ffd23f);animation:crCore 850ms ease-in-out infinite alternate}.crRune{position:absolute;font-size:28px;animation:crFloat 1.2s ease-in-out infinite}.crRune.r1{top:18%;left:17%}.crRune.r2{top:27%;right:18%}.crRune.r3{bottom:22%;left:22%}.crRune.r4{bottom:17%;right:23%}@keyframes crSpin{to{transform:rotate(360deg) scale(1.25);opacity:0}}@keyframes crCore{to{transform:scale(1.12) rotate(3deg)}}@keyframes crFloat{50%{transform:translateY(-28px) rotate(20deg);opacity:.65}}.crMissionClaim{margin-top:12px;width:100%;background:linear-gradient(135deg,#10a86e,#4fe5a2);color:#052114;padding:10px;border-radius:11px;font-weight:1000}.crMissionClaim.claimed{background:#241c2b;color:#8d8098}.crResFlash{animation:crFlash .55s ease}@keyframes crFlash{50%{transform:scale(1.08);filter:brightness(1.8)}}@media(max-width:800px){.crUG{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(s)}
function refreshUI(p){if(p)window.profile=p;const prof=window.profile||{};document.querySelectorAll('#gem-count,#gemCount,[data-resource="gems"]').forEach(e=>e.textContent=Math.max(0,Number(prof.gems)||0));document.querySelectorAll('#gold-count,#goldCount,[data-resource="gold"]').forEach(e=>e.textContent=Math.max(0,Number(prof.gold)||0));document.querySelectorAll('.resources .res').forEach(e=>e.classList.add('crResFlash'));setTimeout(()=>document.querySelectorAll('.resources .res').forEach(e=>e.classList.remove('crResFlash')),650)}
async function pullProfile(){if(!window.sb||!window.user)return null;const q=await window.sb.from('profiles').select('*').eq('id',window.user.id).single();if(!q.error&&q.data){refreshUI(q.data);return q.data}return null}
function findCardsPage(){return [...document.querySelectorAll('.page')].find(p=>/cartes|cards/i.test((p.id||'')+' '+(p.querySelector('.title')?.textContent||'')))}
function openDeck(){css();let m=document.getElementById('crDeckModal');if(!m){m=document.createElement('div');m.id='crDeckModal';m.innerHTML='<div class="crUM"><div class="title" style="margin-top:0"><div><h2>🃏 MODIFIER MON DECK</h2><span>Choisis exactement jusqu’à 8 cartes que tu possèdes.</span></div><button class="btn" id="crDeckX">✕</button></div><button class="btn crBack" id="crDeckBack">← RETOUR AUX CARTES</button><div id="crDeckGrid" class="crUG"></div></div>';document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('on')});m.querySelector('#crDeckX').onclick=()=>m.classList.remove('on');m.querySelector('#crDeckBack').onclick=()=>{m.classList.remove('on');const b=[...document.querySelectorAll('.nav button,.nav a')].find(x=>/cartes/i.test(x.textContent||''));if(b)b.click();else if(typeof window.showPage==='function')window.showPage('cards')}}const d=deck(),set=new Set(d),g=m.querySelector('#crDeckGrid');g.innerHTML=CARDS().filter(owned).map(c=>'<button class="crUC '+(set.has(c.id)?'sel':'')+'" data-id="'+c.id+'"><span class="crBadge">'+(set.has(c.id)?'DANS LE DECK':'')+'</span><div class="e">'+esc(c.emoji||'⚔️')+'</div><b>'+esc(c.name)+'</b><small>'+esc(c.type||'')+' • ⚡ '+(c.cost??'-')+'</small></button>').join('')||'<div class="muted">Aucune carte possédée.</div>';g.querySelectorAll('[data-id]').forEach(b=>b.onclick=async()=>{const id=Number(b.dataset.id),x=deck(),i=x.indexOf(id);if(i>=0)x.splice(i,1);else{if(x.length>=8)return toast('Deck complet : retire une carte avant d’en ajouter une autre.');x.push(id)}await saveDeck(x);openDeck()});m.classList.add('on')}
function hookDeck(){const page=findCardsPage();if(!page)return;let b=[...page.querySelectorAll('.tab,button')].find(x=>/deck/i.test(x.textContent||''));if(!b){const tabs=page.querySelector('.tabs');if(tabs){b=document.createElement('button');b.className='tab';b.textContent='🃏 DECK';tabs.appendChild(b)}}if(b&&!b.dataset.crUltimate){b.dataset.crUltimate='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openDeck()},true)}}
function botThrottle(){if(window.__crBotThrottle)return;window.__crBotThrottle=true;let last=0;const orig=window.deployUnit;if(typeof orig==='function'){window.deployUnit=function(card,x,y,side){if(side==='enemy'){const now=Date.now();const live=[...(window.battle?.units||[])].filter(u=>u&&u.side==='enemy'&&u.hp>0);if(now-last<4000||live.length>=4)return null;last=now}return orig.apply(this,arguments)}}if(typeof window.botDeploy==='function'){const old=window.botDeploy;window.botDeploy=function(){const now=Date.now();if(now-last<4000)return;return old.apply(this,arguments)}}}
function getPackPrice(pack){const vals=[pack?.cost,pack?.price,pack?.gems,pack?.gemCost,pack?.gem_cost,pack?.priceGems];for(const v of vals){const n=Number(v);if(Number.isFinite(n)&&n>0)return n}const label=(pack?.name||pack?.title||'').toString();const nums=label.match(/\b(\d{2,5})\b/);return nums?Number(nums[1]):0}
async function enhancedOpenPack(pack){await pullProfile();const price=getPackPrice(pack);if(price>0&&Number(window.profile?.gems||0)<price)return toast('Pas assez de gemmes 💎 — le pack ne s’ouvre pas et l’animation ne démarre pas.');const modal=document.getElementById('modal'),body=document.getElementById('modalBody'),title=document.getElementById('modalTitle');if(!modal||!body)return window.__crOldOpenPack(pack);if(title)title.textContent='✨ CROWN RIFT PACK';body.innerHTML='<div class="crPackFX"><span class="crRune r1">✦</span><span class="crRune r2">💎</span><span class="crRune r3">✧</span><span class="crRune r4">🔥</span><div><div class="crCore">📦</div><h2>LE RIFT S’OUVRE...</h2><p class="muted">Les sceaux anciens révèlent tes cartes.</p></div></div>';modal.classList.add('show');await new Promise(r=>setTimeout(r,1700));await window.__crOldOpenPack(pack);await pullProfile()}
function hookPack(){const old=window.openPack;if(typeof old!=='function'||old.__crUltimate)return;if(!window.__crOldOpenPack)window.__crOldOpenPack=old;const fn=function(packObj){return enhancedOpenPack(packObj)};fn.__crUltimate=true;window.openPack=fn}
function missionReward(m){const el=m.querySelector('.reward');const n=(el?.textContent||m.textContent||'').match(/\b(\d+)\s*💎?/);return n?Number(n[1]):50}
function hookMissions(){const page=[...document.querySelectorAll('.page')].find(p=>/mission/i.test((p.id||''))||/MISSIONS/i.test(p.querySelector('.title')?.textContent||''));if(!page)return;page.querySelectorAll('.mission').forEach(m=>{if(m.dataset.crMission)return;const text=(m.textContent||'').toLowerCase();const doneClass=m.classList.contains('done');const percent=Number((m.textContent.match(/(\d+)\s*%/)||[])[1]||0);const done=doneClass||percent>=100||/terminée|terminee|compl[eè]te|✅/.test(text);if(!done)return;m.dataset.crMission='1';const b=document.createElement('button');b.className='crMissionClaim';b.textContent='🎁 RÉCUPÉRER';m.appendChild(b);b.onclick=async()=>{if(m.dataset.claimed)return;await pullProfile();const gems=missionReward(m),current=Number(window.profile?.gems||0);if(!window.sb||!window.user)return toast('Connexion nécessaire pour récupérer la récompense.');const q=await window.sb.from('profiles').update({gems:current+gems}).eq('id',window.user.id);if(q.error)return toast('Erreur sauvegarde : '+q.error.message);window.profile.gems=current+gems;refreshUI(window.profile);m.dataset.claimed='1';b.textContent='✅ RÉCUPÉRÉ';b.classList.add('claimed');toast('Mission récupérée : +'+gems+' 💎')}})}
function boot(){css();hookDeck();hookPack();botThrottle();hookMissions();refreshUI(window.profile)}
window.addEventListener('load',()=>setTimeout(boot,1200));setInterval(()=>{if(window.profile){hookDeck();hookPack();hookMissions();botThrottle()}},1800);window.CR_REFRESH_PROFILE=pullProfile;
})();
